// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://zakupki.gov.ru/oos/EATypes/1
package IntegrationEATypes

import (
	"encoding/xml"
	"github.com/gocomply/xsd2go/Xsds/base"
	"github.com/gocomply/xsd2go/Xsds/cmn"
)

// ExportableElements

// CommonInfoCorrectionInfo: Информация об исправлении
type CommonInfoCorrectionInfo struct {
	XMLName xml.Name `xml:"correctionInfo,omitempty"`

	// CorrectionNumber: Номер исправления
	CorrectionNumber int `xml:"correctionNumber"`

	// ParentDocUuid: Уникальный идентификатор документа, на основании которого сформировано исправление
	ParentDocUuid base.GuidType `xml:"parentDocUuid"`

	// ParentDocDate: Дата документа, на основании которого сформировано исправление
	ParentDocDate string `xml:"parentDocDate"`
}

// ContractInfoStageInfo: Информация об этапе контракта, на основании которого сформирован документ
type ContractInfoStageInfo struct {
	XMLName xml.Name `xml:"stageInfo"`

	// Sid: Уникальный идентификатор этапа контракта в ЕИС.
	Sid int64 `xml:"sid"`

	// ExternalSid: Внешний идентификатор этапа
	ExternalSid *base.ExternalIdType `xml:"externalSid,omitempty"`

	// Guid: GUID этапа контракта
	Guid base.GuidType `xml:"guid"`
}

// CommonInfoContractInfo: Информация о контракте
type CommonInfoContractInfo struct {
	XMLName xml.Name `xml:"contractInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// Id: Идентификатор версии контракта
	Id int64 `xml:"id"`

	// VersionNumber: Номер версии контракта
	VersionNumber base.VersionNumberType `xml:"versionNumber"`

	// ContractInfoStageInfo: Информация об этапе контракта, на основании которого сформирован документ
	StageInfo ContractInfoStageInfo `xml:"stageInfo"`
}

// CommonInfoCustomerInfo: Информация о заказчике
type CommonInfoCustomerInfo struct {
	XMLName xml.Name `xml:"customerInfo"`

	// Inn: ИНН
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`

	// Address: Адрес организации
	Address base.Text2000Type `xml:"address"`

	cmn.OrganizationRefType
}

// CommonInfo: Общая информация
type CommonInfo struct {
	XMLName xml.Name `xml:"commonInfo"`

	// DocumentNumber: Номер документа о приемке
	DocumentNumber base.Text1000Type `xml:"documentNumber"`

	// CommonInfoCorrectionInfo: Информация об исправлении
	CorrectionInfo *CommonInfoCorrectionInfo `xml:"correctionInfo,omitempty"`

	// CommonInfoContractInfo: Информация о контракте
	ContractInfo CommonInfoContractInfo `xml:"contractInfo"`

	// IndustrySpecialization: Отраслевая специализация: CONSTRUCTION_WORKS - Строительство; DRUGS_PURCHASE - Лекарственные препараты; RESIDENTIAL_PREMISES_PURCHASE - Приобретение жилых помещений
	IndustrySpecialization *base.IndustrySpecializationType `xml:"industrySpecialization,omitempty"`

	// CommonInfoCustomerInfo: Информация о заказчике
	CustomerInfo CommonInfoCustomerInfo `xml:"customerInfo"`

	// ParticipantInfo: Информация о поставщике
	ParticipantInfo SupplierInfoType `xml:"participantInfo"`

	// Sum: Сумма документа
	Sum base.MoneyMaxLengthToPoint18Type `xml:"sum"`

	// TransferDate: Дата передачи товаров (результатов выполненных работ, оказанных услуг)
	TransferDate string `xml:"transferDate,omitempty"`

	// DeliveryStartDate: Дата начала периода поставки товаров (выполнения работ, оказания услуг)
	DeliveryStartDate string `xml:"deliveryStartDate,omitempty"`

	// DeliveryEndDate: Дата окончания периода поставки товаров (выполнения работ, оказания услуг)
	DeliveryEndDate string `xml:"deliveryEndDate,omitempty"`

	// AdditionalInfo: Дополнительная информация
	AdditionalInfo *base.Text2000Type `xml:"additionalInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT"`
}

// SupplierTitleInfo: Сведения о документе, содержащем инфомацию поставщика
type SupplierTitleInfo struct {
	XMLName xml.Name `xml:"supplierTitleInfo"`

	// Uuid: Уникальный идентификатор документа поставщика
	Uuid base.GuidType `xml:",any"`
}

// CommonInfoContractInfo1: Информация о контракте
type CommonInfoContractInfo1 struct {
	XMLName xml.Name `xml:"contractInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:",any"`
}

// CommonInfo1: Общая информация
type CommonInfo1 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// CommonInfoContractInfo: Информация о контракте
	ContractInfo CommonInfoContractInfo `xml:"contractInfo"`

	// AcceptanceResultCode: Итог приемки/рассмотрения. Допустимые значения: 0 - Возвращено для уточнения; 1 - Товары (работы, услуги) приняты без расхождений (претензий); 2 - Товары (работы, услуги) приняты с расхождениями (претензией); 3 - Товары (работы, услуги) не приняты
	AcceptanceResultCode AcceptanceResultCodeType `xml:"acceptanceResultCode"`

	// AcceptedSum: Принятая сумма по документу
	AcceptedSum base.MoneyMaxLengthToPoint18Type `xml:"acceptedSum"`

	// AcceptanceDate: Дата получения товаров
	AcceptanceDate string `xml:"acceptanceDate,omitempty"`

	// AdditionalInfo: Дополнительная информация
	AdditionalInfo *base.Text2000Type `xml:"additionalInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT"`
}

// SpendingFundsInfo: Сведения о направлениях расходования средств
type SpendingFundsInfo struct {
	XMLName xml.Name `xml:"spendingFundsInfo"`

	// Description: Описание сведений о направлениях расходования средств
	Description base.Text2000Type `xml:"description"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT"`
}

// PrintFormInfoSignature: Электронная подпись электронного документа
type PrintFormInfoSignature struct {
	XMLName xml.Name `xml:"signature,omitempty"`

	// Type: Тип электронной подписи: CAdES-BES; CAdES-A
	Type base.SignatureType `xml:"type,attr,omitempty"`

	Text string `xml:",chardata"`
}

// PrintFormInfo: Печатная форма документа
type PrintFormInfo struct {
	XMLName xml.Name `xml:"printFormInfo,omitempty"`

	// PrintFormInfoSignature: Электронная подпись электронного документа
	Signature *PrintFormInfoSignature `xml:"signature,omitempty"`

	// FileType: Тип файла электронного документа
	FileType base.PrintFormFileType `xml:"fileType"`

	// Content: Содержимое файла электронного документа. Контролируется заполнение поля content или contentID при приёме. Поле не заполняется при передаче
	Content string `xml:"content,omitempty"`

	// ContentId: Уникальный идентификатор контента прикрепленного документа в ЕИС. Поле не заполняется при передаче
	ContentId *base.GuidType `xml:"contentId,omitempty"`

	// Url: Ссылка для скачивания электронного документа. При приеме в ЕИС контролируется недопустимость заполнения данного поля. Поле заполняется при передаче
	Url *base.HrefType `xml:"url,omitempty"`
}

// ContractInfo: Сведения о государственном контракте
type ContractInfo struct {
	XMLName xml.Name `xml:"contractInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// Number: Номер контракта
	Number base.Text100Type `xml:"number"`

	// StartDate: Дата начала исполнения контракта
	StartDate string `xml:"startDate"`

	// EndDate: Дата завершения исполнения контракта
	EndDate string `xml:"endDate"`

	// Price: Цена контракта
	Price base.MoneyMaxLengthToPoint18Type `xml:"price"`

	// PurchaseCode: Идентификационный код закупки из контракта
	PurchaseCode *base.IkzCodeType `xml:"purchaseCode,omitempty"`
}

// SubcontractInfo: Сведения о субподрядном договоре
type SubcontractInfo struct {
	XMLName xml.Name `xml:"subcontractInfo"`

	// NumberSc: Номер субподрядного договора
	NumberSc base.Text100Type `xml:"numberSC"`

	// StartDateSc: Дата начала исполнения договора
	StartDateSc string `xml:"startDateSC"`

	// EndDateSc: Дата завершения исполнения договора
	EndDateSc string `xml:"endDateSC"`

	// PriceSc: Цена договора
	PriceSc base.MoneyMaxLengthToPoint18Type `xml:"priceSC"`
}

// LegalEntityRfinfo: Юридическое лицо РФ
type LegalEntityRfinfo struct {
	XMLName xml.Name `xml:"legalEntityRFInfo"`

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// Inn: ИНН
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`

	// IsMajorTaxPayerKpp: Признак указания КПП крупнейшего налогоплательщика
	IsMajorTaxPayerKpp *bool `xml:"isMajorTaxPayerKPP,omitempty"`
}

// FilialLegalEntityRfinfo: Филиал юридического лица РФ
type FilialLegalEntityRfinfo struct {
	XMLName xml.Name `xml:"filialLegalEntityRFInfo"`

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// Inn: ИНН
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`
}

// IndividualPersonRfinfo: Физическое лицо РФ
type IndividualPersonRfinfo struct {
	XMLName xml.Name `xml:"individualPersonRFInfo"`

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// Inn: ИНН
	Inn base.InnIndividualType `xml:"INN"`
}

// LegalEntityForeignStateInRafpinfo: Аккредитованный филиал или представительство иностранного юридического лица
type LegalEntityForeignStateInRafpinfo struct {
	XMLName xml.Name `xml:"legalEntityForeignStateInRAFPInfo"`

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// Inn: ИНН
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`
}

// IndividualPersonForeignStateInfo: Физическое лицо иностранного государства
type IndividualPersonForeignStateInfo struct {
	XMLName xml.Name `xml:"individualPersonForeignStateInfo"`

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// Inn: ИНН
	Inn base.InnIndividualType `xml:"INN"`
}

// XSD ComplexType declarations

// ElActUnstructuredSupplierTitleType: Тип: Документ о приемке в неструктурированной форме (информация поставщика)
type ElActUnstructuredSupplierTitleType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа
	Uuid base.GuidType `xml:"uuid"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ElActDocsInfo: Файлы документа о приемке
	ElActDocsInfo cmn.AttachmentListType `xml:"elActDocsInfo"`

	// AdditionalDocsInfo: Дополнительные документы
	AdditionalDocsInfo *cmn.AttachmentListType `xml:"additionalDocsInfo,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком. При передаче заполняется поле "Содержимое файла электронного документа" (content)
	ParPrintFormInfo *cmn.ExtPrintFormType `xml:"parPrintFormInfo,omitempty"`
}

// ElActUnstructuredCustomerTitleType: Тип: Документ о приемке в неструктурированной форме (информация заказчика)
type ElActUnstructuredCustomerTitleType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа
	Uuid base.GuidType `xml:"uuid"`

	// SupplierTitleInfo: Сведения о документе, содержащем инфомацию поставщика
	SupplierTitleInfo SupplierTitleInfo `xml:"supplierTitleInfo"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ElActDocsInfo: Файлы документа о приемке
	ElActDocsInfo *cmn.AttachmentListType `xml:"elActDocsInfo,omitempty"`

	// AdditionalDocsInfo: Дополнительные документы заказчика
	AdditionalDocsInfo *cmn.AttachmentListWithEakindType `xml:"additionalDocsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа, подписанного заказчиком. При передаче заполняется поле "Содержимое файла электронного документа" (content)
	PrintFormInfo *cmn.ExtPrintFormType `xml:"printFormInfo,omitempty"`
}

// ElActSpendingFundsInfoType: Тип: Сведения о направлениях расходования средств
type ElActSpendingFundsInfoType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа
	Uuid base.GuidType `xml:"uuid"`

	// SpendingFundsInfo: Сведения о направлениях расходования средств
	SpendingFundsInfo SpendingFundsInfo `xml:"spendingFundsInfo"`

	// AdditionalDocsInfo: Дополнительные документы
	AdditionalDocsInfo *cmn.AttachmentListType `xml:"additionalDocsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *PrintFormInfo `xml:"printFormInfo,omitempty"`

	// ContractInfo: Сведения о государственном контракте
	ContractInfo *ContractInfo `xml:"contractInfo,omitempty"`

	// SubcontractInfo: Сведения о субподрядном договоре
	SubcontractInfo *SubcontractInfo `xml:"subcontractInfo,omitempty"`
}

// SupplierInfoType: Тип: Информация о поставщике
type SupplierInfoType struct {
	XMLName xml.Name

	// EruzRegistryNum: Номер реестровой записи в ЕРУЗ
	EruzRegistryNum *base.EruzRegistryNumType `xml:"eruzRegistryNum,omitempty"`

	// LegalEntityRfinfo: Юридическое лицо РФ
	LegalEntityRfinfo *LegalEntityRfinfo `xml:"legalEntityRFInfo,omitempty"`

	// FilialLegalEntityRfinfo: Филиал юридического лица РФ
	FilialLegalEntityRfinfo *FilialLegalEntityRfinfo `xml:"filialLegalEntityRFInfo,omitempty"`

	// IndividualPersonRfinfo: Физическое лицо РФ
	IndividualPersonRfinfo *IndividualPersonRfinfo `xml:"individualPersonRFInfo,omitempty"`

	// LegalEntityForeignStateInRafpinfo: Аккредитованный филиал или представительство иностранного юридического лица
	LegalEntityForeignStateInRafpinfo *LegalEntityForeignStateInRafpinfo `xml:"legalEntityForeignStateInRAFPInfo,omitempty"`

	// IndividualPersonForeignStateInfo: Физическое лицо иностранного государства
	IndividualPersonForeignStateInfo *IndividualPersonForeignStateInfo `xml:"individualPersonForeignStateInfo,omitempty"`
}

// XSD SimpleType declarations

// AcceptanceResultCodeType: Тип: Код итога приемки: 0 - Возвращено для уточнения; 1 - Товары (работы, услуги) приняты без расхождений (претензий); 2 - Товары (работы, услуги) приняты с расхождениями (претензией); 3 - Товары (работы, услуги) не приняты
type AcceptanceResultCodeType string

const AcceptanceResultCodeType0 AcceptanceResultCodeType = "0"

const AcceptanceResultCodeType1 AcceptanceResultCodeType = "1"

const AcceptanceResultCodeType2 AcceptanceResultCodeType = "2"

const AcceptanceResultCodeType3 AcceptanceResultCodeType = "3"
