// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://zakupki.gov.ru/oos/URTypes/1
package IntegrationURTypes

import (
	"encoding/xml"
	"github.com/gocomply/xsd2go/XsdGoFiles/base"
	"github.com/gocomply/xsd2go/XsdGoFiles/cmn"
)

// ExportableElements

// CommonInfo: Общая информация
type CommonInfo struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// ParticipantInfo: Поставщик. Игнорируется при приеме, заполняется автоматически на основании реестрового номера контракта
	ParticipantInfo *cmn.ParticipantUrtype `xml:"participantInfo,omitempty"`

	// DocType: Вид уведомления. Игнорируется при приеме, заполняется автоматически значением "Решение об одностороннем отказе" на основании справочника "Типы документов одностороннего отказа и претензионной переписки по результатам электронных процедур" (nsiURDocTypes)
	DocType *cmn.NsiUrdocTypesRef `xml:"docType,omitempty"`

	// NoticeNum: Номер уведомления
	NoticeNum *base.Text100Type `xml:"noticeNum,omitempty"`

	// EstimatedEffectiveDate: Предполагаемая дата вступления решения в силу
	EstimatedEffectiveDate string `xml:"estimatedEffectiveDate"`

	// RepeatedViolation: Признак повторного нарушения
	RepeatedViolation *bool `xml:"repeatedViolation,omitempty"`

	// TerminationReason: Причина расторжения контракта
	TerminationReason base.Text2000Type `xml:"terminationReason"`

	// AddInfo: Дополнительная информация
	AddInfo *base.Text2000Type `xml:"addInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT,omitempty"`

	// DocPublishDate: Дата публикации. Игнорируется при приеме, заполняется при передаче датой из квитка, полученного из ЛКП
	DocPublishDate string `xml:"docPublishDate,omitempty"`
}

// PrintFormFieldsInfo: Дополнительная информация для печатной формы. Игнорируется при приёме
type PrintFormFieldsInfo struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// RecipientName: Наименование получателя
	RecipientName *base.Text2000Type `xml:",any,omitempty"`
}

// CommonInfo1: Общая информация
type CommonInfo1 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// ParticipantInfo: Поставщик. Игнорируется при приеме, заполняется автоматически на основании реестрового номера контракта
	ParticipantInfo *cmn.ParticipantUrtype `xml:"participantInfo,omitempty"`

	// DocType: Вид уведомления. Игнорируется при приеме, заполняется автоматически значением "Уведомление претензионной переписки" на основании справочника "Типы документов одностороннего отказа и претензионной переписки по результатам электронных процедур" (nsiURDocTypes)
	DocType *cmn.NsiUrdocTypesRef `xml:"docType,omitempty"`

	// AddInfo: Дополнительная информация
	AddInfo *base.Text2000Type `xml:"addInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT,omitempty"`

	// DocPublishDate: Дата публикации. Игнорируется при приеме, заполняется при передаче датой из квитка, полученного из ЛКП
	DocPublishDate string `xml:"docPublishDate,omitempty"`
}

// CommonInfo2: Общая информация
type CommonInfo2 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// ParticipantInfo: Поставщик. Игнорируется при приеме, заполняется автоматически на основании реестрового номера контракта
	ParticipantInfo *cmn.ParticipantUrtype `xml:"participantInfo,omitempty"`

	// DocType: Вид уведомления. Игнорируется при приеме, заполняется автоматически значением "Извещение об отмене решения об одностороннем отказе от исполнения контракта" на основании справочника "Типы документов одностороннего отказа и претензионной переписки по результатам электронных процедур" (nsiURDocTypes)
	DocType *cmn.NsiUrdocTypesRef `xml:"docType,omitempty"`

	// CancelDate: Дата принятия решения об отмене
	CancelDate string `xml:"cancelDate"`

	// AddInfo: Дополнительная информация
	AddInfo *base.Text2000Type `xml:"addInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT,omitempty"`

	// DocPublishDate: Дата публикации. Игнорируется при приеме, заполняется при передаче датой из квитка, полученного из ЛКП
	DocPublishDate string `xml:"docPublishDate,omitempty"`

	// RejectDocInfo: Требование о признании недействительным решения об одностороннем отказе
	RejectDocInfo *RejectDocInfoType `xml:"rejectDocInfo,omitempty"`
}

// PrintFormFieldsInfo1: Дополнительная информация для печатной формы. Игнорируется при приёме
type PrintFormFieldsInfo1 struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// RecipientName: Наименование получателя
	RecipientName *base.Text2000Type `xml:"recipientName,omitempty"`

	// NoticeNum: Номер уведомления
	NoticeNum *base.Text100Type `xml:"noticeNum,omitempty"`
}

// CommonInfo3: Общая информация
type CommonInfo3 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// ParticipantInfo: Поставщик. Игнорируется при приеме, заполняется автоматически на основании реестрового номера контракта
	ParticipantInfo *cmn.ParticipantUrtype `xml:"participantInfo,omitempty"`

	// DocType: Вид уведомления. Игнорируется при приеме, заполняется автоматически значением "Решение об одностороннем отказе" на основании справочника "Типы документов одностороннего отказа и претензионной переписки по результатам электронных процедур" (nsiURDocTypes)
	DocType *cmn.NsiUrdocTypesRef `xml:"docType,omitempty"`

	// NoticeNum: Номер уведомления
	NoticeNum *base.Text100Type `xml:"noticeNum,omitempty"`

	// EstimatedEffectiveDate: Предполагаемая дата вступления решения в силу
	EstimatedEffectiveDate string `xml:"estimatedEffectiveDate"`

	// TerminationReason: Причина расторжения контракта
	TerminationReason base.Text2000Type `xml:"terminationReason"`

	// AddInfo: Дополнительная информация
	AddInfo *base.Text2000Type `xml:"addInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT,omitempty"`

	// DocPublishDate: Дата публикации. Игнорируется при приеме, заполняется при передаче датой из квитка, полученного из ЛКП
	DocPublishDate string `xml:"docPublishDate,omitempty"`
}

// PrintFormFieldsInfo2: Дополнительная информация для печатной формы. Игнорируется при приёме
type PrintFormFieldsInfo2 struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// RecipientName: Наименование получателя
	RecipientName *base.Text2000Type `xml:",any,omitempty"`
}

// CommonInfo4: Общая информация
type CommonInfo4 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Реестровый номер контракта. При приеме проверяется наличие контракта в одном из следующих статусов: - Размещено; - Исполнение; - Исполнение завершено; - Исполнение прекращено; И принадлежность поставщика к данному контракту
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// ParticipantInfo: Поставщик. Игнорируется при приеме, заполняется автоматически на основании реестрового номера контракта
	ParticipantInfo *cmn.ParticipantUrtype `xml:"participantInfo,omitempty"`

	// DocType: Вид уведомления. Игнорируется при приеме, заполняется автоматически значением "Уведомление претензионной переписки" на основании справочника "Типы документов одностороннего отказа и претензионной переписки по результатам электронных процедур" (nsiURDocTypes)
	DocType *cmn.NsiUrdocTypesRef `xml:"docType,omitempty"`

	// AddInfo: Дополнительная информация
	AddInfo *base.Text2000Type `xml:"addInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT,omitempty"`

	// DocPublishDate: Дата публикации. Игнорируется при приеме, заполняется при передаче датой из квитка, полученного из ЛКП
	DocPublishDate string `xml:"docPublishDate,omitempty"`
}

// CommonInfo5: Общая информация
type CommonInfo5 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// ParticipantInfo: Поставщик. Игнорируется при приеме, заполняется автоматически на основании реестрового номера контракта
	ParticipantInfo *cmn.ParticipantUrtype `xml:"participantInfo,omitempty"`

	// DocType: Вид уведомления. Игнорируется при приеме, заполняется автоматически значением "Извещение об отмене решения об одностороннем отказе от исполнения контракта" на основании справочника "Типы документов одностороннего отказа и претензионной переписки по результатам электронных процедур" (nsiURDocTypes)
	DocType *cmn.NsiUrdocTypesRef `xml:"docType,omitempty"`

	// CancelDate: Дата принятия решения об отмене
	CancelDate string `xml:"cancelDate"`

	// AddInfo: Дополнительная информация
	AddInfo *base.Text2000Type `xml:"addInfo,omitempty"`

	// SignDt: Дата подписания документа
	SignDt string `xml:"signDT,omitempty"`

	// DocPublishDate: Дата публикации. Игнорируется при приеме, заполняется при передаче датой из квитка, полученного из ЛКП
	DocPublishDate string `xml:"docPublishDate,omitempty"`

	// RejectDocInfo: Требование о признании недействительным решения об одностороннем отказе
	RejectDocInfo *RejectDocInfoType `xml:"rejectDocInfo,omitempty"`
}

// PrintFormFieldsInfo3: Дополнительная информация для печатной формы. Игнорируется при приёме
type PrintFormFieldsInfo3 struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// RecipientName: Наименование получателя
	RecipientName *base.Text2000Type `xml:"recipientName,omitempty"`

	// NoticeNum: Номер уведомления
	NoticeNum *base.Text100Type `xml:"noticeNum,omitempty"`
}

// XSD ComplexType declarations

// ContractProcedureUnilateralRefusalType: Тип: Решение об одностороннем отказе от исполнения контракта, сформированное заказчиком
type ContractProcedureUnilateralRefusalType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// AttachmentsInfo: Файлы решения об одностороннем отказе
	AttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormWithDsuidType `xml:"printFormInfo,omitempty"`

	// PrintFormHtmlinfo: Печатная форма документа в HTML-представлении
	PrintFormHtmlinfo *cmn.AttachmentWithDsuidType `xml:"printFormHTMLInfo,omitempty"`

	// PowerOfAttorneyInfo: Сведения о доверенности. Игнорируется при приеме, заполняется при передаче
	PowerOfAttorneyInfo *cmn.WithFirstPoattorneyType `xml:"powerOfAttorneyInfo,omitempty"`

	// PrintFormFieldsInfo: Дополнительная информация для печатной формы. Игнорируется при приёме
	PrintFormFieldsInfo *PrintFormFieldsInfo `xml:"printFormFieldsInfo,omitempty"`
}

// ClaimsCorrespondenceNoticeType: Тип: Уведомление в рамках претензионной переписки, сформированное заказчиком
type ClaimsCorrespondenceNoticeType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RefusalUuid: Уникальный идентификатор документа решения об одностороннем отказе от исполнения контракта (решение может быть сформировано как заказчиком, так и поставщиком), на основании которого сформировано уведомление в рамках претензионной переписки
	RefusalUuid *base.GuidType `xml:"refusalUuid,omitempty"`

	// ParentNoticeUuid: Уникальный идентификатор родительского документа уведомления в рамках претензионной переписки
	ParentNoticeUuid *base.GuidType `xml:"parentNoticeUuid,omitempty"`

	// CommonInfo1: Общая информация
	CommonInfo CommonInfo1 `xml:"commonInfo"`

	// AttachmentsInfo: Файлы уведомления
	AttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormWithDsuidType `xml:"printFormInfo,omitempty"`

	// PrintFormHtmlinfo: Печатная форма документа в HTML-представлении
	PrintFormHtmlinfo *cmn.AttachmentWithDsuidType `xml:"printFormHTMLInfo,omitempty"`

	// PowerOfAttorneyInfo: Сведения о доверенности. Игнорируется при приеме, заполняется при передаче
	PowerOfAttorneyInfo *cmn.WithFirstPoattorneyType `xml:"powerOfAttorneyInfo,omitempty"`
}

// ContractProcedureUnilateralRefusalCancelType: Тип: Извещение об отмене решения об одностороннем отказе от исполнения контракта, сформированное заказчиком
type ContractProcedureUnilateralRefusalCancelType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RefusalUuid: Уникальный идентификатор документа реешения об одностороннем отказе от исполнения контракта, на основании которого сформировано уведомление в рамках претензионной переписки, сформированное заказчиком
	RefusalUuid base.GuidType `xml:"refusalUuid"`

	// CommonInfo2: Общая информация
	CommonInfo CommonInfo2 `xml:"commonInfo"`

	// NoticeAttachmentsInfo: Уведомление об устранении причины одностороннего отказа
	NoticeAttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"noticeAttachmentsInfo,omitempty"`

	// AttachmentsInfo: Файлы извещения об отмене решения об одностороннем отказе
	AttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormWithDsuidType `xml:"printFormInfo,omitempty"`

	// PrintFormHtmlinfo: Печатная форма документа в HTML-представлении
	PrintFormHtmlinfo *cmn.AttachmentWithDsuidType `xml:"printFormHTMLInfo,omitempty"`

	// PowerOfAttorneyInfo: Сведения о доверенности. Игнорируется при приеме, заполняется при передаче
	PowerOfAttorneyInfo *cmn.WithFirstPoattorneyType `xml:"powerOfAttorneyInfo,omitempty"`

	// PrintFormFieldsInfo1: Дополнительная информация для печатной формы. Игнорируется при приёме
	PrintFormFieldsInfo *PrintFormFieldsInfo1 `xml:"printFormFieldsInfo,omitempty"`
}

// ParContractProcedureUnilateralRefusalType: Тип: Решение об одностороннем отказе от исполнения контракта, сформированное поставщиком
type ParContractProcedureUnilateralRefusalType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП
	LkpUuid *base.GuidType `xml:"lkpUuid,omitempty"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// CommonInfo3: Общая информация
	CommonInfo CommonInfo3 `xml:"commonInfo"`

	// AttachmentsInfo: Файлы решения об одностороннем отказе
	AttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком. При передаче заполняется поле "Содержимое файла электронного документа" (content)
	ParPrintFormInfo *cmn.PrintFormWithDsuidType `xml:"parPrintFormInfo,omitempty"`

	// ParPrintFormHtmlinfo: Печатная форма документа в HTML-представлении
	ParPrintFormHtmlinfo *cmn.AttachmentWithDsuidType `xml:"parPrintFormHTMLInfo,omitempty"`

	// PowerOfAttorneyInfo: Сведения о доверенности. Игнорируется при приеме, заполняется при передаче
	PowerOfAttorneyInfo *cmn.WithFirstPoattorneyType `xml:"powerOfAttorneyInfo,omitempty"`

	// PrintFormFieldsInfo2: Дополнительная информация для печатной формы. Игнорируется при приёме
	PrintFormFieldsInfo *PrintFormFieldsInfo2 `xml:"printFormFieldsInfo,omitempty"`
}

// ParClaimsCorrespondenceNoticeType: Тип: Уведомление в рамках претензионной переписки, сформированное поставщиком
type ParClaimsCorrespondenceNoticeType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП. Игнорируется при приеме проектов. Заполняется при размещении
	LkpUuid *base.GuidType `xml:"lkpUuid,omitempty"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RefusalLkpUuid: Уникальный идентификатор документа решения об одностороннем отказе от исполнения контракта (решение может быть сформировано как заказчиком, так и поставщиком), на основании которого сформировано уведомление в рамках претензионной переписки
	RefusalLkpUuid *base.GuidType `xml:"refusalLkpUuid,omitempty"`

	// ParentNoticeLkpUuid: Уникальный идентификатор родительского документа уведомления в рамках претензионной переписки
	ParentNoticeLkpUuid *base.GuidType `xml:"parentNoticeLkpUuid,omitempty"`

	// CommonInfo4: Общая информация
	CommonInfo CommonInfo4 `xml:"commonInfo"`

	// AttachmentsInfo: Файлы уведомления
	AttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком. При передаче заполняется поле "Содержимое файла электронного документа" (content). Игнорируется при приеме проектов. Заполняется при размещении
	ParPrintFormInfo *cmn.PrintFormWithDsuidType `xml:"parPrintFormInfo,omitempty"`

	// ParPrintFormHtmlinfo: Печатная форма документа в HTML-представлении
	ParPrintFormHtmlinfo *cmn.AttachmentWithDsuidType `xml:"parPrintFormHTMLInfo,omitempty"`

	// PowerOfAttorneyInfo: Сведения о доверенности. Игнорируется при приеме, заполняется при передаче
	PowerOfAttorneyInfo *cmn.WithFirstPoattorneyType `xml:"powerOfAttorneyInfo,omitempty"`
}

// ParContractProcedureUnilateralRefusalCancelType: Тип: Извещение об отмене решения об одностороннем отказе от исполнения контракта, сформированное поставщиком
type ParContractProcedureUnilateralRefusalCancelType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП
	LkpUuid *base.GuidType `xml:"lkpUuid,omitempty"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RefusalLkpUuid: Уникальный идентификатор документа реешения об одностороннем отказе от исполнения контракта, сформированное поставщиком, на основании которого сформировано извещение об отмене решения об одностороннем отказе от исполнения контракта, сформированное поставщиком
	RefusalLkpUuid base.GuidType `xml:"refusalLkpUuid"`

	// CommonInfo5: Общая информация
	CommonInfo CommonInfo5 `xml:"commonInfo"`

	// NoticeAttachmentsInfo: Уведомление об устранении причины одностороннего отказа
	NoticeAttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"noticeAttachmentsInfo,omitempty"`

	// AttachmentsInfo: Файлы извещения об отмене решения об одностороннем отказе
	AttachmentsInfo *cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком. При передаче заполняется поле "Содержимое файла электронного документа" (content)
	ParPrintFormInfo *cmn.PrintFormWithDsuidType `xml:"parPrintFormInfo,omitempty"`

	// ParPrintFormHtmlinfo: Печатная форма документа в HTML-представлении
	ParPrintFormHtmlinfo *cmn.AttachmentWithDsuidType `xml:"parPrintFormHTMLInfo,omitempty"`

	// PowerOfAttorneyInfo: Сведения о доверенности. Игнорируется при приеме, заполняется при передаче
	PowerOfAttorneyInfo *cmn.WithFirstPoattorneyType `xml:"powerOfAttorneyInfo,omitempty"`

	// PrintFormFieldsInfo3: Дополнительная информация для печатной формы. Игнорируется при приёме
	PrintFormFieldsInfo *PrintFormFieldsInfo3 `xml:"printFormFieldsInfo,omitempty"`
}

// SupplierDataChangeNoticeType: Тип: Уведомление об изменении реквизитов поставщика по контракту
type SupplierDataChangeNoticeType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// RegNumber: Реестровый номер контракта
	RegNumber base.ContractRegNumType `xml:"regNumber"`

	// NewKpp: Новый КПП в соответствии с регистрационными данными ЕРУЗ
	NewKpp base.KppType `xml:"newKPP"`
}

// RejectDocInfoType: Тип: Требование о признании недействительным решения об одностороннем отказе
type RejectDocInfoType struct {
	XMLName xml.Name

	// DocNumber: Номер документа
	DocNumber base.Text255Type `xml:"docNumber"`

	// DocDate: Дата документа
	DocDate string `xml:"docDate"`

	// AttachmentsInfo: Информация о признании недействительным решения об одностороннем отказе
	AttachmentsInfo cmn.AttachmentListWithDsuidType `xml:"attachmentsInfo"`
}

// XSD SimpleType declarations
