// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://zakupki.gov.ru/oos/KOTypes/1
package IntegrationKOTypes

import (
	"encoding/xml"
	"github.com/gocomply/xsd2go/Xsds/base"
	"github.com/gocomply/xsd2go/Xsds/cmn"
)

// Violations: Выявленные в процессе обработки нарушения и ошибки
type Violations struct {
	XMLName xml.Name `xml:"violations,omitempty"`

	Violation []ViolationType `xml:",any"`
}

// CommonInfo: Общая информация
type CommonInfo struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Номер реестровой записи жалобы. Не заполняется при подписании жалобы поставщиком. Присваивается и заполняется при размещении жалобы в РЖ
	RegNumber *base.ControlRegistersRegNumberType `xml:"regNumber,omitempty"`

	// VersionNumber: Номер версии
	VersionNumber base.VersionNumberType `xml:"versionNumber"`

	// PublishDt: Дата размещения документа в ЕИС. Не заполняется при подписании жалобы поставщиком. Заполняется датой размещении жалобы в РЖ
	PublishDt string `xml:"publishDT,omitempty"`

	// AppealActionCode: Обжалуемое действие. Допустимые значения: DOCS - жалоба на положения извещения об осуществлении закупки,; ACCR - жалоба на действия (бездействие) оператора электронной площадки совершенные при аккредитации участника закупки на электронной площадке, при размещении на электронной площадке предварительного предложения; COMP - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные после даты и времени окончания срока подачи заявок; DEAL - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные при заключении контракта после размещения в единой информационной системе протокола подведения итогов определения поставщика (подрядчика, исполнителя); CNCL - Жалоба на расторжение контракта. Устарело, не применяется, начиная с версии 13.1
	AppealActionCode *base.AppealActionCodeType `xml:"appealActionCode,omitempty"`

	// AppealActionInfo: Обжалуемое действие. Ссылка на справочник "Обжалуемые действия" (nsiAppleadActions) Обязательно для заполнения, начиная с версии 13.1
	AppealActionInfo *base.AppleadActionRef `xml:"appealActionInfo,omitempty"`

	// Text: Содержание жалобы
	Text base.Text2000Type `xml:"text"`
}

// ObjectInfoPurchaseInfo: Закупка
type ObjectInfoPurchaseInfo struct {
	XMLName xml.Name `xml:"purchaseInfo"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode *base.IkzCodeType `xml:"purchaseCode,omitempty"`

	// PurchaseNumber: Номер извещения о проведении
	PurchaseNumber *base.PurchaseNumberType `xml:"purchaseNumber,omitempty"`

	// PurchaseName: Наименование закупки
	PurchaseName base.Text2000Type `xml:"purchaseName"`

	// PurchasePlacingDate: Дата размещения извещения об осуществлении закупки
	PurchasePlacingDate string `xml:"purchasePlacingDate,omitempty"`

	// FinalProtocolPlacingDate: Дата размещения итогового протокола определения поставщика
	FinalProtocolPlacingDate string `xml:"finalProtocolPlacingDate,omitempty"`

	// IsGoz: Закупка товаров, работ, услуг по государственному оборонному заказу в соответствии с ФЗ № 275-ФЗ от 29 декабря 2012 г
	IsGoz *bool `xml:"isGOZ,omitempty"`
}

// ObjectInfo: Предмет жалобы
type ObjectInfo struct {
	XMLName xml.Name `xml:"objectInfo,omitempty"`

	// ObjectInfoPurchaseInfo: Закупка
	PurchaseInfo ObjectInfoPurchaseInfo `xml:",any"`
}

// SubjectsInfo: Информация о субъектах жалобы
type SubjectsInfo struct {
	XMLName xml.Name `xml:"subjectsInfo"`

	// SubjectInfo: Информация о субъекте жалобы
	SubjectInfo []SubjectInfoType `xml:",any"`
}

// ExperienceConfirmationInfo: Подтверждение опыта участника закупок
type ExperienceConfirmationInfo struct {
	XMLName xml.Name `xml:"experienceConfirmationInfo,omitempty"`

	// ContractRegNum44: Реестровый номер контракта по 44-ФЗ
	ContractRegNum44 []base.ContractRegNumType `xml:"contractRegNum44,omitempty"`

	// AgreementRegNum223: Реестровый номер договора по 223-ФЗ
	AgreementRegNum223 *Agreement223RegNumType `xml:"agreementRegNum223,omitempty"`
}

// ContactInfo: Контактные данные участника закупок
type ContactInfo struct {
	XMLName xml.Name `xml:"contactInfo"`

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`
}

// NoticeOrgsInfo: Организации, в адрес которых осуществляется рассылка уведомлений Игнорируется при приеме проекта из внешней системы
type NoticeOrgsInfo struct {
	XMLName xml.Name `xml:"noticeOrgsInfo,omitempty"`

	// NoticeOrgInfo: Организация, в адрес которой осуществляется рассылка уведомлений
	NoticeOrgInfo []base.OrganizationRef `xml:",any"`
}

// PrintFormFieldsInfoSubjectsInfo: Информация о субъектах жалобы
type PrintFormFieldsInfoSubjectsInfo struct {
	XMLName xml.Name `xml:"subjectsInfo,omitempty"`

	// SubjectInfo: Информация о субъекте жалобы
	SubjectInfo []SubjectInfoType `xml:",any"`
}

// PrintFormFieldsInfo: Дополнительная информация для печатной формы
type PrintFormFieldsInfo struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// Koname: Наименование контрольного органа в сфере закупок
	Koname *base.Text2000Type `xml:"KOName,omitempty"`

	// ContractorName: Наименование участника закупки (поставщика, подрядчика, исполнителя)
	ContractorName *base.Text2000Type `xml:"contractorName,omitempty"`

	// ContractorFioinfo: ФИО участника закупки (поставщика, подрядчика, исполнителя)
	ContractorFioinfo *cmn.PersonType `xml:"contractorFIOInfo,omitempty"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode *base.IkzCodeType `xml:"purchaseCode,omitempty"`

	// PrintFormFieldsInfoSubjectsInfo: Информация о субъектах жалобы
	SubjectsInfo *PrintFormFieldsInfoSubjectsInfo `xml:"subjectsInfo,omitempty"`

	// AppealActionCode: Обжалуемое действие. Допустимые значения: DOCS - жалоба на положения извещения об осуществлении закупки, документации о закупке; ACCR - жалоба на действия (бездействие) оператора электронной площадки, совершенные при аккредитации участника закупки на электронной площадке; COMP - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные после даты и времени окончания срока подачи заявок; DEAL - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные при заключении контракта после размещения в единой информационной системе протокола подведения итогов определения поставщика (подрядчика, исполнителя), подписания такого протокола (при проведении закрытого конкурса, закрытого аукциона); CNCL - Жалоба на расторжение контракта Устарело, не применяется, начиная с версии 13.1
	AppealActionCode *base.AppealActionCodeType `xml:"appealActionCode,omitempty"`

	// AppealActionInfo: Обжалуемое действие. Ссылка на справочник "Обжалуемые действия" (nsiAppleadActions) Обязательно для заполнения, начиная с версии 13.1
	AppealActionInfo *base.AppleadActionRef `xml:"appealActionInfo,omitempty"`
}

// CommonInfoConsiderationKoinfo: Орган, осуществляющий принятие жалобы к рассмотрению
type CommonInfoConsiderationKoinfo struct {
	XMLName xml.Name `xml:"considerationKOInfo"`

	// Inn: ИНН. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	Inn *base.InnOrganizationType `xml:"INN,omitempty"`

	// Kpp: КПП. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// RegNum: Код по СПЗ. В случае если организация идентифицируется по коду СвР, а код СПЗ неизвестен, необходимо заполнить данное поле значением 00000000000, и обязательно указать код СвР
	RegNum SpzNumType `xml:"regNum"`

	// ConsRegistryNum: Код по Сводному Реестру. Должен быть заполнен в случае, если в поле regNum указано значение 00000000000
	ConsRegistryNum *ConsRegistryNumType `xml:"consRegistryNum,omitempty"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	FullName *Text2000Type `xml:"fullName,omitempty"`
}

// CommonInfoDecisionPlaceByGarinfo: Место рассмотрения жалобы по ГАР. Контролируется на обязательность заполнения, начиная с версии 15.2
type CommonInfoDecisionPlaceByGarinfo struct {
	XMLName xml.Name `xml:"decisionPlaceByGARInfo,omitempty"`

	// Garinfo: Код ГАР. Контролируется на присутствие GUID ГАР в справочнике "Государственный адресный реестр (ГАР)"
	Garinfo *cmn.Gartype `xml:"GARInfo,omitempty"`

	// DeliveryPlace: Дополнительная информация об адресе
	DeliveryPlace *base.Text2000Type `xml:"deliveryPlace,omitempty"`
}

// CommonInfoVideoConfInfo: Возможно использование видеоконференц-связи
type CommonInfoVideoConfInfo struct {
	XMLName xml.Name `xml:"videoConfInfo,omitempty"`

	// VideoConfUrl: Ссылка для подключения к видеоконференц-связи
	VideoConfUrl *base.HrefType `xml:"videoConfUrl,omitempty"`

	// NotPublishedOnEis: Информация не будет размещена на официальном сайте ЕИС. Не может быть заполнен при приеме, заполняется при передаче, в случае если информация не должна быть размещена в открытой части ЕИС
	NotPublishedOnEis *bool `xml:"notPublishedOnEIS,omitempty"`
}

// CommonInfo1: Общая информация о принятии жалобы к рассмотрению
type CommonInfo1 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// CommonInfoConsiderationKoinfo: Орган, осуществляющий принятие жалобы к рассмотрению
	ConsiderationKoinfo CommonInfoConsiderationKoinfo `xml:"considerationKOInfo"`

	// PlanDecisionDate: Дата и время рассмотрения жалобы
	PlanDecisionDate string `xml:"planDecisionDate"`

	// PublishDate: Дата размещения информация о принятии жалобы к рассмотрению. Игнорируется при приеме. Заполняется автоматически датой размещения
	PublishDate string `xml:"publishDate,omitempty"`

	// DecisionPlace: Место рассмотрения жалобы Не используется, начиная с версии 15.2
	DecisionPlace *KladrPlaceType `xml:"decisionPlace,omitempty"`

	// CommonInfoDecisionPlaceByGarinfo: Место рассмотрения жалобы по ГАР. Контролируется на обязательность заполнения, начиная с версии 15.2
	DecisionPlaceByGarinfo *CommonInfoDecisionPlaceByGarinfo `xml:"decisionPlaceByGARInfo,omitempty"`

	// CommonInfoVideoConfInfo: Возможно использование видеоконференц-связи
	VideoConfInfo *CommonInfoVideoConfInfo `xml:"videoConfInfo,omitempty"`

	// DecisionComment: Комментарий по решению
	DecisionComment *base.Text2000Type `xml:"decisionComment,omitempty"`
}

// ComplaintInfo: Информация о жалобе, по которой формируется информация о принятии к рассмотрению
type ComplaintInfo struct {
	XMLName xml.Name `xml:"complaintInfo"`

	// RegNumber: Номер реестровой записи жалобы
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// ReceiptDate: Дата поступления жалобы. Игнорируется при приеме, заполняется автоматически датой размещения жалобы
	ReceiptDate string `xml:"receiptDate,omitempty"`
}

// CommonInfoConsiderationKoinfo1: Орган, осуществляющий отказ в рассмотрении жалобы
type CommonInfoConsiderationKoinfo1 struct {
	XMLName xml.Name `xml:"considerationKOInfo"`

	// Inn: ИНН. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	Inn *base.InnOrganizationType `xml:"INN,omitempty"`

	// Kpp: КПП. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// RegNum: Код по СПЗ. В случае если организация идентифицируется по коду СвР, а код СПЗ неизвестен, необходимо заполнить данное поле значением 00000000000, и обязательно указать код СвР
	RegNum SpzNumType `xml:"regNum"`

	// ConsRegistryNum: Код по Сводному Реестру. Должен быть заполнен в случае, если в поле regNum указано значение 00000000000
	ConsRegistryNum *ConsRegistryNumType `xml:"consRegistryNum,omitempty"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	FullName *Text2000Type `xml:"fullName,omitempty"`
}

// CommonInfo2: Общая информация об отказе в рассмотрении жалобы
type CommonInfo2 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// CommonInfoConsiderationKoinfo: Орган, осуществляющий отказ в рассмотрении жалобы
	ConsiderationKoinfo CommonInfoConsiderationKoinfo `xml:"considerationKOInfo"`

	// PublishDate: Дата размещения информация об отказе в рассмотрении жалобы. Игнорируется при приеме. Заполняется автоматически датой размещения
	PublishDate string `xml:"publishDate,omitempty"`

	// RefusalReasonInfo: Основание для отказа в принятии жалобы к рассмотрению по существу. При приеме код контролируется на присутствие в справочнике "Основания для отказа в принятии жалобы к рассмотрению по существу" (nsiComplaintRefusalReason)
	RefusalReasonInfo cmn.ComplaintRefusalReasonRefType `xml:"refusalReasonInfo"`

	// DecisionComment: Комментарий по решению
	DecisionComment *base.Text2000Type `xml:"decisionComment,omitempty"`
}

// ComplaintInfo1: Информация о жалобе, по которой формируется информация об отказе в рассмотрении
type ComplaintInfo1 struct {
	XMLName xml.Name `xml:"complaintInfo"`

	// RegNumber: Номер реестровой записи жалобы
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// ReceiptDate: Дата поступления жалобы. Игнорируется при приеме, заполняется автоматически датой размещения жалобы
	ReceiptDate string `xml:"receiptDate,omitempty"`
}

// NoticeTypeInfoComplaintInfo: Уведомление о размещеннии в ЕИС электронной жалобы, сформированной в ЛКП
type NoticeTypeInfoComplaintInfo struct {
	XMLName xml.Name `xml:"complaintInfo"`

	// LkpUuid: Идентификатор жалобы в ЛКП
	LkpUuid base.GuidType `xml:",any"`
}

// NoticeTypeInfoComplaintCancelInfo: Уведомление о размещении отзыва электронной жалобы, сформированной в ЛКП
type NoticeTypeInfoComplaintCancelInfo struct {
	XMLName xml.Name `xml:"complaintCancelInfo"`

	ComplaintCancel bool `xml:",any"`
}

// NoticeTypeInfoComplaintAcceptInfo: Уведомление о принятии к рассмотрению электронной жалобы, сформированной в ЛКП
type NoticeTypeInfoComplaintAcceptInfo struct {
	XMLName xml.Name `xml:"complaintAcceptInfo"`

	// PlanDecisionDate: Дата и время рассмотрения жалобы
	PlanDecisionDate string `xml:"planDecisionDate"`

	// Url: Ссылка для подключения к видеоконференц-связи
	Url *base.HrefType `xml:"url,omitempty"`

	// DecisionPlace: Место рассмотрения жалобы
	DecisionPlace *base.Text2000Type `xml:"decisionPlace,omitempty"`
}

// NoticeTypeInfoComplaintRefusalInfo: Уведомление об отказе в рассмотрении электронной жалобы, сформированной в ЛКП
type NoticeTypeInfoComplaintRefusalInfo struct {
	XMLName xml.Name `xml:"complaintRefusalInfo"`

	ComplaintRefusal bool `xml:",any"`
}

// NoticeTypeInfoComplaintTransferInfo: Уведомление о передаче жалобы по подведомственности / ведомственной принадлежности
type NoticeTypeInfoComplaintTransferInfo struct {
	XMLName xml.Name `xml:"complaintTransferInfo"`

	// ReceivingKoinfo: Контрольный орган, принявший жалобу
	ReceivingKoinfo base.OrganizationRef `xml:"receivingKOInfo"`

	// TransferType: Тип передачи. Допустимые значения: DT - Передача жалобы по ведомственной принадлежности; TR - Передача жалобы по подведомственности
	TransferType base.TransferNoticeType `xml:"transferType"`
}

// NoticeTypeInfoUnplannedCheckInfo: Уведомление о размещении внеплановой проверки
type NoticeTypeInfoUnplannedCheckInfo struct {
	XMLName xml.Name `xml:"unplannedCheckInfo"`

	// RegNumber: Номер реестровой записи внеплановой проверки
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// InspectionDate: Дата и время проведения проверки
	InspectionDate string `xml:"inspectionDate,omitempty"`

	// InspectionPlace: Место проведения проверки
	InspectionPlace *base.Text2000Type `xml:"inspectionPlace,omitempty"`

	// VideoConfUrl: Ссылка для подключения к видеоконференц-связи
	VideoConfUrl *base.HrefType `xml:"videoConfUrl,omitempty"`
}

// NoticeTypeInfoUnplannedCheckCancelInfo: Уведомление о размещении отмены внеплановой проверки
type NoticeTypeInfoUnplannedCheckCancelInfo struct {
	XMLName xml.Name `xml:"unplannedCheckCancelInfo"`

	// RegNumber: Номер реестровой записи внеплановой проверки
	RegNumber base.ControlRegistersRegNumberType `xml:",any"`
}

// NoticeTypeInfoCheckResultInfo: Уведомление о размещении результата контроля
type NoticeTypeInfoCheckResultInfo struct {
	XMLName xml.Name `xml:"checkResultInfo"`

	// RegNumber: Номер реестровой записи результата контроля
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// CheckResultType: Тип резульата контроля. Допустимые значения: - complaint - результат контроля по жалобе; - checkResult - результат контроля по внеплановой проверке
	CheckResultType ControlResultType `xml:"checkResultType"`
}

// NoticeTypeInfoCheckResultCancelInfo: Уведомление о размещении отмены результата контроля
type NoticeTypeInfoCheckResultCancelInfo struct {
	XMLName xml.Name `xml:"checkResultCancelInfo"`

	// RegNumber: Номер реестровой записи результата контроля
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// CheckResultType: Тип резульата контроля. Допустимые значения: - complaint - результат контроля по жалобе; - checkResult - результат контроля по внеплановой проверке
	CheckResultType ControlResultType `xml:"checkResultType"`
}

// NoticeTypeInfo: Информация о типе события
type NoticeTypeInfo struct {
	XMLName xml.Name `xml:"noticeTypeInfo"`

	// NoticeTypeInfoComplaintInfo: Уведомление о размещеннии в ЕИС электронной жалобы, сформированной в ЛКП
	ComplaintInfo *NoticeTypeInfoComplaintInfo `xml:"complaintInfo,omitempty"`

	// NoticeTypeInfoComplaintCancelInfo: Уведомление о размещении отзыва электронной жалобы, сформированной в ЛКП
	ComplaintCancelInfo *NoticeTypeInfoComplaintCancelInfo `xml:"complaintCancelInfo,omitempty"`

	// NoticeTypeInfoComplaintAcceptInfo: Уведомление о принятии к рассмотрению электронной жалобы, сформированной в ЛКП
	ComplaintAcceptInfo *NoticeTypeInfoComplaintAcceptInfo `xml:"complaintAcceptInfo,omitempty"`

	// NoticeTypeInfoComplaintRefusalInfo: Уведомление об отказе в рассмотрении электронной жалобы, сформированной в ЛКП
	ComplaintRefusalInfo *NoticeTypeInfoComplaintRefusalInfo `xml:"complaintRefusalInfo,omitempty"`

	// NoticeTypeInfoComplaintTransferInfo: Уведомление о передаче жалобы по подведомственности / ведомственной принадлежности
	ComplaintTransferInfo *NoticeTypeInfoComplaintTransferInfo `xml:"complaintTransferInfo,omitempty"`

	// NoticeTypeInfoUnplannedCheckInfo: Уведомление о размещении внеплановой проверки
	UnplannedCheckInfo *NoticeTypeInfoUnplannedCheckInfo `xml:"unplannedCheckInfo,omitempty"`

	// NoticeTypeInfoUnplannedCheckCancelInfo: Уведомление о размещении отмены внеплановой проверки
	UnplannedCheckCancelInfo *NoticeTypeInfoUnplannedCheckCancelInfo `xml:"unplannedCheckCancelInfo,omitempty"`

	// NoticeTypeInfoCheckResultInfo: Уведомление о размещении результата контроля
	CheckResultInfo *NoticeTypeInfoCheckResultInfo `xml:"checkResultInfo,omitempty"`

	// NoticeTypeInfoCheckResultCancelInfo: Уведомление о размещении отмены результата контроля
	CheckResultCancelInfo *NoticeTypeInfoCheckResultCancelInfo `xml:"checkResultCancelInfo,omitempty"`
}

// SignatureInfo: Электронная подпись электронного документа в ХД
type SignatureInfo struct {
	XMLName xml.Name `xml:"signatureInfo,omitempty"`

	// Type: Тип электронной подписи: CAdES-BES; CAdES-A
	Type base.SignatureType `xml:"type,attr,omitempty"`

	// Url: Ссылка для скачивания электронной подписи в ХД. Поле не заполняется при приеме
	Url *base.HrefType `xml:"url,omitempty"`

	// DsUid: Идентификатор электронной подписи в ХД. Поле не заполняется при приеме.
	DsUid *base.GuidType `xml:"dsUid,omitempty"`
}

// CommonInfo3: Общая информация
type CommonInfo3 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Номер реестровой записи жалобы. Не заполняется при подписании жалобы поставщиком. Присваивается и заполняется при размещении жалобы в РЖ
	RegNumber *base.ControlRegistersRegNumberType `xml:"regNumber,omitempty"`

	// VersionNumber: Номер версии
	VersionNumber base.VersionNumberType `xml:"versionNumber"`

	// PublishDt: Дата размещения документа в ЕИС. Не заполняется при подписании жалобы поставщиком. Заполняется датой размещении жалобы в РЖ
	PublishDt string `xml:"publishDT,omitempty"`

	// AppealActionCode: Обжалуемое действие. Допустимые значения: DOCS - жалоба на положения извещения об осуществлении закупки,; ACCR - жалоба на действия (бездействие) оператора электронной площадки совершенные при аккредитации участника закупки на электронной площадке, при размещении на электронной площадке предварительного предложения; COMP - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные после даты и времени окончания срока подачи заявок; DEAL - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные при заключении контракта после размещения в единой информационной системе протокола подведения итогов определения поставщика (подрядчика, исполнителя); CNCL - Жалоба на расторжение контракта. Устарело, не применяется, начиная с версии 13.1
	AppealActionCode *base.AppealActionCodeType `xml:"appealActionCode,omitempty"`

	// AppealActionInfo: Обжалуемое действие. Ссылка на справочник "Обжалуемые действия" (nsiAppleadActions) Обязательно для заполнения, начиная с версии 13.1
	AppealActionInfo *base.AppleadActionRef `xml:"appealActionInfo,omitempty"`

	// Text: Содержание жалобы
	Text base.Text2000Type `xml:"text"`
}

// ObjectInfoPurchaseInfo1: Закупка
type ObjectInfoPurchaseInfo1 struct {
	XMLName xml.Name `xml:"purchaseInfo"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode *base.IkzCodeType `xml:"purchaseCode,omitempty"`

	// PurchaseNumber: Номер извещения о проведении
	PurchaseNumber *base.PurchaseNumberType `xml:"purchaseNumber,omitempty"`

	// PurchaseName: Наименование закупки
	PurchaseName base.Text2000Type `xml:"purchaseName"`

	// PurchasePlacingDate: Дата размещения извещения об осуществлении закупки
	PurchasePlacingDate string `xml:"purchasePlacingDate,omitempty"`

	// FinalProtocolPlacingDate: Дата размещения итогового протокола определения поставщика
	FinalProtocolPlacingDate string `xml:"finalProtocolPlacingDate,omitempty"`

	// IsGoz: Закупка товаров, работ, услуг по государственному оборонному заказу в соответствии с ФЗ № 275-ФЗ от 29 декабря 2012 г
	IsGoz *bool `xml:"isGOZ,omitempty"`
}

// ObjectInfo1: Предмет жалобы
type ObjectInfo1 struct {
	XMLName xml.Name `xml:"objectInfo,omitempty"`

	// ObjectInfoPurchaseInfo: Закупка
	PurchaseInfo ObjectInfoPurchaseInfo `xml:",any"`
}

// SubjectsInfo1: Информация о субъектах жалобы
type SubjectsInfo1 struct {
	XMLName xml.Name `xml:"subjectsInfo"`

	// SubjectInfo: Информация о субъекте жалобы
	SubjectInfo []SubjectInfoType `xml:",any"`
}

// ExperienceConfirmationInfo1: Подтверждение опыта участника закупок
type ExperienceConfirmationInfo1 struct {
	XMLName xml.Name `xml:"experienceConfirmationInfo,omitempty"`

	// ContractRegNum44: Реестровый номер контракта по 44-ФЗ
	ContractRegNum44 []base.ContractRegNumType `xml:"contractRegNum44,omitempty"`

	// AgreementRegNum223: Реестровый номер договора по 223-ФЗ
	AgreementRegNum223 *Agreement223RegNumType `xml:"agreementRegNum223,omitempty"`
}

// ContactInfo1: Контактные данные участника закупок
type ContactInfo1 struct {
	XMLName xml.Name `xml:"contactInfo"`

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`
}

// NoticeOrgsInfo1: Организации, в адрес которых осуществляется рассылка уведомлений Игнорируется при приеме проекта из внешней системы
type NoticeOrgsInfo1 struct {
	XMLName xml.Name `xml:"noticeOrgsInfo,omitempty"`

	// NoticeOrgInfo: Организация, в адрес которой осуществляется рассылка уведомлений
	NoticeOrgInfo []base.OrganizationRef `xml:",any"`
}

// PrintFormFieldsInfoSubjectsInfo1: Информация о субъектах жалобы
type PrintFormFieldsInfoSubjectsInfo1 struct {
	XMLName xml.Name `xml:"subjectsInfo,omitempty"`

	// SubjectInfo: Информация о субъекте жалобы
	SubjectInfo []SubjectInfoType `xml:",any"`
}

// PrintFormFieldsInfo1: Дополнительная информация для печатной формы
type PrintFormFieldsInfo1 struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// Koname: Наименование контрольного органа в сфере закупок
	Koname *base.Text2000Type `xml:"KOName,omitempty"`

	// ContractorName: Наименование участника закупки (поставщика, подрядчика, исполнителя)
	ContractorName *base.Text2000Type `xml:"contractorName,omitempty"`

	// ContractorFioinfo: ФИО участника закупки (поставщика, подрядчика, исполнителя)
	ContractorFioinfo *cmn.PersonType `xml:"contractorFIOInfo,omitempty"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode *base.IkzCodeType `xml:"purchaseCode,omitempty"`

	// PrintFormFieldsInfoSubjectsInfo: Информация о субъектах жалобы
	SubjectsInfo *PrintFormFieldsInfoSubjectsInfo `xml:"subjectsInfo,omitempty"`

	// AppealActionCode: Обжалуемое действие. Допустимые значения: DOCS - жалоба на положения извещения об осуществлении закупки, документации о закупке; ACCR - жалоба на действия (бездействие) оператора электронной площадки, совершенные при аккредитации участника закупки на электронной площадке; COMP - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные после даты и времени окончания срока подачи заявок; DEAL - жалоба на действия (бездействие) субъекта (субъектов) контроля, совершенные при заключении контракта после размещения в единой информационной системе протокола подведения итогов определения поставщика (подрядчика, исполнителя), подписания такого протокола (при проведении закрытого конкурса, закрытого аукциона); CNCL - Жалоба на расторжение контракта Устарело, не применяется, начиная с версии 13.1
	AppealActionCode *base.AppealActionCodeType `xml:"appealActionCode,omitempty"`

	// AppealActionInfo: Обжалуемое действие. Ссылка на справочник "Обжалуемые действия" (nsiAppleadActions) Обязательно для заполнения, начиная с версии 13.1
	AppealActionInfo *base.AppleadActionRef `xml:"appealActionInfo,omitempty"`
}

// CommonInfo4: Общая информация
type CommonInfo4 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Номер реестровой записи обращения
	RegNumber base.ApprovalRegNumType `xml:"regNumber"`

	// VersionNumber: Номер версии
	VersionNumber string `xml:"versionNumber"`

	// PublishDt: Дата направления обращения
	PublishDt string `xml:"publishDT,omitempty"`
}

// CustomerInfo: Информация о заказчике
type CustomerInfo struct {
	XMLName xml.Name `xml:"customerInfo"`

	// Oktmo: ОКТМО
	Oktmo base.Oktmoref `xml:"OKTMO"`

	// Email: Электронная почта
	Email *base.EMailType `xml:"email,omitempty"`

	// ShortName: Краткое наименование
	ShortName *base.Text2000Type `xml:"shortName,omitempty"`

	// Inn: ИНН организации
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП организации
	Kpp base.KppType `xml:"KPP"`

	// Address: Адрес места нахождения
	Address base.Text2000Type `xml:"address"`

	// RegNum: Код по СПЗ. В случае если организация идентифицируется по коду СвР, а код СПЗ неизвестен, необходимо заполнить данное поле значением 00000000000, и обязательно указать код СвР
	RegNum SpzNumType `xml:"regNum"`

	// ConsRegistryNum: Код по Сводному Реестру. Должен быть заполнен в случае, если в поле regNum указано значение 00000000000
	ConsRegistryNum *ConsRegistryNumType `xml:"consRegistryNum,omitempty"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	FullName *Text2000Type `xml:"fullName,omitempty"`
}

// PowersCustomerOrgInfo: Сведения об организации, действующей за заказчика (УО. УУ. ОПЗ)
type PowersCustomerOrgInfo struct {
	XMLName xml.Name `xml:"powersCustomerOrgInfo,omitempty"`

	// Oktmo: ОКТМО
	Oktmo base.Oktmoref `xml:"OKTMO"`

	// Email: Электронная почта
	Email *base.EMailType `xml:"email,omitempty"`

	// ShortName: Краткое наименование
	ShortName *base.Text2000Type `xml:"shortName,omitempty"`

	// Inn: ИНН организации
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП организации
	Kpp base.KppType `xml:"KPP"`

	// Address: Адрес места нахождения
	Address base.Text2000Type `xml:"address"`

	// RegNum: Код по СПЗ. В случае если организация идентифицируется по коду СвР, а код СПЗ неизвестен, необходимо заполнить данное поле значением 00000000000, и обязательно указать код СвР
	RegNum SpzNumType `xml:"regNum"`

	// ConsRegistryNum: Код по Сводному Реестру. Должен быть заполнен в случае, если в поле regNum указано значение 00000000000
	ConsRegistryNum *ConsRegistryNumType `xml:"consRegistryNum,omitempty"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	FullName *Text2000Type `xml:"fullName,omitempty"`
}

// SingleParContractApprovalInfoSingleParticipantInfo: Информация о единственном поставщике
type SingleParContractApprovalInfoSingleParticipantInfo struct {
	XMLName xml.Name `xml:"singleParticipantInfo"`

	// LegalEntityRfinfo: Юридическое лицо РФ
	LegalEntityRfinfo *ApprovalLegalEntityRfinfoType `xml:"legalEntityRFInfo,omitempty"`

	// LegalEntityForeignStateInfo: Юридическое лицо иностранного государства
	LegalEntityForeignStateInfo *ApprovalLegalEntityForeignStateInfoType `xml:"legalEntityForeignStateInfo,omitempty"`

	// IndividualPersonRfinfo: Физическое лицо РФ
	IndividualPersonRfinfo *ApprovalIndividualPersonRfinfoType `xml:"individualPersonRFInfo,omitempty"`

	// IndividualPersonForeignStateInfo: Физическое лицо иностранного государства
	IndividualPersonForeignStateInfo *ApprovalIndividualPersonForeignStateInfoType `xml:"individualPersonForeignStateInfo,omitempty"`
}

// SingleParContractApprovalInfoPurchaseInfo: Закупка
type SingleParContractApprovalInfoPurchaseInfo struct {
	XMLName xml.Name `xml:"purchaseInfo"`

	// PurchaseNumber: Реестровый номер закупки
	PurchaseNumber base.PurchaseNumberType `xml:"purchaseNumber"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode base.IkzCodeType `xml:"purchaseCode"`

	// PurchaseName: Наименование закупки
	PurchaseName base.Text2000Type `xml:"purchaseName"`

	// MaxPrice: Начальная (максимальная) цена контрактов/Максимальное значение цены контракта
	MaxPrice base.MoneyType `xml:"maxPrice"`

	// InitialAmount: Начальная сумма цен единиц товара, работы, услуги
	InitialAmount *base.MoneyType `xml:"initialAmount,omitempty"`

	// ContractPriceFormula: Формула цены контракта
	ContractPriceFormula *base.Text2000Type `xml:"contractPriceFormula,omitempty"`

	// OfferPrice: Цена контракта, предложенная участником закупки
	OfferPrice base.MoneyType `xml:"offerPrice"`

	// TotalSum: Сумма цен единиц, товара, работы, услуги, предложенная участником
	TotalSum base.MoneyType `xml:"totalSum"`

	// Currency: Валюта закупки
	Currency base.CurrencyRef `xml:"currency"`

	// FailedProcedurePprf916Info: Ссылка на справочник "Несостоявшиеся процедуры по ПП РФ 961" (NSI_FAILED_PROCEDURE_PP_RF_916)
	FailedProcedurePprf916Info base.FailedProcedurePprf916Ref `xml:"failedProcedurePPRF916Info"`
}

// ApprovalInfoSingleParContractApprovalInfo: Обращение о согласовании заключения контракта с единственным поставщиком (подрядчиком, исполнителем)
type ApprovalInfoSingleParContractApprovalInfo struct {
	XMLName xml.Name `xml:"singleParContractApprovalInfo"`

	// SingleParContractApprovalInfoSingleParticipantInfo: Информация о единственном поставщике
	SingleParticipantInfo SingleParContractApprovalInfoSingleParticipantInfo `xml:"singleParticipantInfo"`

	// SingleParContractApprovalInfoPurchaseInfo: Закупка
	PurchaseInfo SingleParContractApprovalInfoPurchaseInfo `xml:"purchaseInfo"`
}

// OtherInfoFounderInfo: Учредитель
type OtherInfoFounderInfo struct {
	XMLName xml.Name `xml:"founderInfo"`

	// FullName: Наименование/ФИО
	FullName base.Text1000Type `xml:"fullName"`

	// Kpp: КПП
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// FounderType: Вид учредителя: Допустимые значения: FOUNDER - Учредитель; PARTICIPANT - Участник; MEMBER - Член коллегиального исполнительного органа
	FounderType string `xml:"founderType"`

	// Inn: ИНН
	Inn *base.InnType `xml:"INN,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`
}

// OtherInfoManagingOrganizationInfo: Управляющая организация
type OtherInfoManagingOrganizationInfo struct {
	XMLName xml.Name `xml:"managingOrganizationInfo"`

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// Kpp: КПП
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// Inn: ИНН
	Inn *base.InnOrganizationType `xml:"INN,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`
}

// OtherInfoWithoutAttorneyPersonInfo: Лицо, имеющее право действовать без доверенности
type OtherInfoWithoutAttorneyPersonInfo struct {
	XMLName xml.Name `xml:"withoutAttorneyPersonInfo"`

	// FullName: ФИО
	FullName base.Text1000Type `xml:"fullName"`

	// Inn: ИНН
	Inn base.InnIndividualType `xml:"INN"`
}

// OthersInfoOtherInfo: Иное лицо
type OthersInfoOtherInfo struct {
	XMLName xml.Name `xml:"otherInfo"`

	// OtherInfoFounderInfo: Учредитель
	FounderInfo *OtherInfoFounderInfo `xml:"founderInfo,omitempty"`

	// OtherInfoManagingOrganizationInfo: Управляющая организация
	ManagingOrganizationInfo *OtherInfoManagingOrganizationInfo `xml:"managingOrganizationInfo,omitempty"`

	// OtherInfoWithoutAttorneyPersonInfo: Лицо, имеющее право действовать без доверенности
	WithoutAttorneyPersonInfo *OtherInfoWithoutAttorneyPersonInfo `xml:"withoutAttorneyPersonInfo,omitempty"`
}

// ParticipantInfoOthersInfo: Иные лица
type ParticipantInfoOthersInfo struct {
	XMLName xml.Name `xml:"othersInfo,omitempty"`

	// OthersInfoOtherInfo: Иное лицо
	OtherInfo []OthersInfoOtherInfo `xml:",any"`
}

// UnfairSupplier2022ApprovalInfoParticipantInfo: Информация об участнике закупки, поставщике, подрядчике, исполнителе
type UnfairSupplier2022ApprovalInfoParticipantInfo struct {
	XMLName xml.Name `xml:"participantInfo"`

	// ParticipantInfoOthersInfo: Иные лица
	OthersInfo *ParticipantInfoOthersInfo `xml:"othersInfo,omitempty"`

	// LegalEntityRfinfo: Юридическое лицо РФ
	LegalEntityRfinfo *ApprovalLegalEntityRfinfoType `xml:"legalEntityRFInfo,omitempty"`

	// LegalEntityForeignStateInfo: Юридическое лицо иностранного государства
	LegalEntityForeignStateInfo *ApprovalLegalEntityForeignStateInfoType `xml:"legalEntityForeignStateInfo,omitempty"`

	// IndividualPersonRfinfo: Физическое лицо РФ
	IndividualPersonRfinfo *ApprovalIndividualPersonRfinfoType `xml:"individualPersonRFInfo,omitempty"`

	// IndividualPersonForeignStateInfo: Физическое лицо иностранного государства
	IndividualPersonForeignStateInfo *ApprovalIndividualPersonForeignStateInfoType `xml:"individualPersonForeignStateInfo,omitempty"`
}

// PurchaseInfoContractInfo: Сведения о контракте
type PurchaseInfoContractInfo struct {
	XMLName xml.Name `xml:"contractInfo,omitempty"`

	// Price: Значение цены контракта в валюте контракта
	Price base.MoneyPositiveType `xml:"price"`

	// Currency: Валюта контракта
	Currency base.CurrencyRef `xml:"currency"`

	// EndDate: Дата окончания исполнения контракта
	EndDate string `xml:"endDate"`

	// TerminationDate: Дата расторжения контракта
	TerminationDate string `xml:"terminationDate,omitempty"`
}

// UnfairSupplier2022ApprovalInfoPurchaseInfo: Закупка
type UnfairSupplier2022ApprovalInfoPurchaseInfo struct {
	XMLName xml.Name `xml:"purchaseInfo"`

	// PurchaseNumber: Реестровый номер закупки
	PurchaseNumber base.PurchaseNumberType `xml:"purchaseNumber"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode base.IkzCodeType `xml:"purchaseCode"`

	// PurchaseName: Наименование закупки
	PurchaseName base.Text2000Type `xml:"purchaseName"`

	// MaxPrice: Начальная (максимальная) цена контрактов/Максимальное значение цены контракта
	MaxPrice base.MoneyType `xml:"maxPrice"`

	// Currency: Валюта закупки
	Currency base.CurrencyRef `xml:"currency"`

	// TypeAppealPprf1078Info: Ссылка на справочник "Коды, установленные для случая направления обращения ППРФ 1078" (NSI_TYPE_APPEAL_PPRF_1078)
	TypeAppealPprf1078Info base.TypeAppealPprf1078Ref `xml:"typeAppealPPRF1078Info"`

	// PurchaseInfoContractInfo: Сведения о контракте
	ContractInfo *PurchaseInfoContractInfo `xml:"contractInfo,omitempty"`
}

// ApprovalInfoUnfairSupplier2022ApprovalInfo: Обращение о включении в РНП
type ApprovalInfoUnfairSupplier2022ApprovalInfo struct {
	XMLName xml.Name `xml:"unfairSupplier2022ApprovalInfo"`

	// UnfairSupplier2022ApprovalInfoParticipantInfo: Информация об участнике закупки, поставщике, подрядчике, исполнителе
	ParticipantInfo UnfairSupplier2022ApprovalInfoParticipantInfo `xml:"participantInfo"`

	// UnfairSupplier2022ApprovalInfoPurchaseInfo: Закупка
	PurchaseInfo UnfairSupplier2022ApprovalInfoPurchaseInfo `xml:"purchaseInfo"`

	// ArbitrationourtUrl: Адрес страницы официального сайта арбитражного суда в информационно-телекоммуникационной сети "Интернет", на которой размещено решение суда о расторжении контракта в связи с существенным нарушением поставщиком (подрядчиком, исполнителем) условий контракта
	ArbitrationourtUrl *base.Text2000Type `xml:"arbitrationСourtURL,omitempty"`
}

// ApprovalInfo: Информация об обращении
type ApprovalInfo struct {
	XMLName xml.Name `xml:"approvalInfo"`

	// ApprovalInfoSingleParContractApprovalInfo: Обращение о согласовании заключения контракта с единственным поставщиком (подрядчиком, исполнителем)
	SingleParContractApprovalInfo *ApprovalInfoSingleParContractApprovalInfo `xml:"singleParContractApprovalInfo,omitempty"`

	// ApprovalInfoUnfairSupplier2022ApprovalInfo: Обращение о включении в РНП
	UnfairSupplier2022ApprovalInfo *ApprovalInfoUnfairSupplier2022ApprovalInfo `xml:"unfairSupplier2022ApprovalInfo,omitempty"`
}

// ApprovalCommonInfo: Общая информация об обращении
type ApprovalCommonInfo struct {
	XMLName xml.Name `xml:"approvalCommonInfo"`

	// RegNumber: Номер реестровой записи обращения
	RegNumber base.ApprovalRegNumType `xml:"regNumber"`

	// PublishDt: Дата направления обращения
	PublishDt string `xml:"publishDT,omitempty"`
}

// PrintFormFieldsInfoParticipantInfo: Информация об участнике закупки, поставщике, подрядчике, исполнителе
type PrintFormFieldsInfoParticipantInfo struct {
	XMLName xml.Name `xml:"participantInfo,omitempty"`

	// FullName: Полное наименование
	FullName *base.Text2000Type `xml:"fullName,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.TaxPayerCode `xml:"taxPayerCode,omitempty"`

	// Inn: ИНН
	Inn *base.InnType `xml:"INN,omitempty"`

	// Kpp: КПП
	Kpp *base.KppType `xml:"KPP,omitempty"`
}

// PrintFormFieldsInfo2: Дополнительная информация для печатной формы
type PrintFormFieldsInfo2 struct {
	XMLName xml.Name `xml:"printFormFieldsInfo,omitempty"`

	// ApprovalType: Тип обращения Допустимые значения: singleParContract - обращение о согласовании заключения контракта с единственным поставщиком (подрядчиком, исполнителем); unfairSupplier2022 - обращение о включении в РНП
	ApprovalType *ApprovalTypeType `xml:"approvalType,omitempty"`

	// NotificationText: Уведомление
	NotificationText *base.Text2000Type `xml:"notificationText,omitempty"`

	// PrintFormFieldsInfoParticipantInfo: Информация об участнике закупки, поставщике, подрядчике, исполнителе
	ParticipantInfo *PrintFormFieldsInfoParticipantInfo `xml:"participantInfo,omitempty"`
}

// CommonInfo5: Общая информация
type CommonInfo5 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Номер реестровой записи
	RegNumber base.UnfairSupplier2022RegNumType `xml:"regNumber"`

	// VersionNumber: Номер версии
	VersionNumber string `xml:"versionNumber"`

	// PublishDt: Дата размещения текущей версии документа
	PublishDt string `xml:"publishDT"`

	// FirstVersionPublishDt: Дата размещения первой версии документа
	FirstVersionPublishDt string `xml:"firstVersionPublishDT"`

	// OccurrenceReasonDate: Дата принятия решения о включении в Реестр
	OccurrenceReasonDate string `xml:"occurrenceReasonDate,omitempty"`

	// AppealSubmissionDate: Дата подачи обращения о включении в Реестр
	AppealSubmissionDate string `xml:"appealSubmissionDate,omitempty"`
}

// CreateReasonInfo: Информация о причинах для внесения в Реестр
type CreateReasonInfo struct {
	XMLName xml.Name `xml:"createReasonInfo"`

	// CreateReason: Причина для внесения в Реестр. Допустимые значения: WINNER_DEVIATION - уклонение победителя от заключения контракта ONE_WINNER_DEVIATION - уклонение единственного участника от заключения контракта PARTICIPANT_DEVIATION_IF_WINNER_DEVIATION - уклонение участника размещения заказа от заключения контракта в случае, когда победитель уклонился от заключения контракта CANCEL_CONTRACT - расторжение контракта
	CreateReason base.UnfairSupplier2022CreateReasonEnum `xml:",any"`
}

// FoundersType: Тип лица
type FoundersType struct {
	XMLName xml.Name `xml:"type,omitempty"`

	// Code: Код по справочнику "Типы иных лиц, добавляемых в РНП"
	Code base.RnpothersCodeType `xml:"code"`

	// Name: Наименование по справочнику "Типы иных лиц, добавляемых в РНП"
	Name *base.Text1000Type `xml:"name,omitempty"`
}

// UnfairSupplierInfoFounders: Информация об иных лицах, включаемых в Реестр
type UnfairSupplierInfoFounders struct {
	XMLName xml.Name `xml:"founders,omitempty"`

	// FullName: Наименование/ФИО
	FullName base.Text1000Type `xml:"fullName"`

	// UnfairSupplierInfoFoundersType: Тип лица
	Type *UnfairSupplierInfoFoundersType `xml:"type,omitempty"`

	// Inn: ИНН
	Inn *base.InnType `xml:"INN,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`

	// IncorrectInnorTaxPayerCode: ИНН или Код налогоплательщика в стране регистрации или его аналог некорректен или отсутствует в БД Реестра
	IncorrectInnorTaxPayerCode *bool `xml:"incorrectINNOrTaxPayerCode,omitempty"`
}

// UnfairSupplierInfoLegalEntityRfinfo: Юридическое лицо РФ
type UnfairSupplierInfoLegalEntityRfinfo struct {
	XMLName xml.Name `xml:"legalEntityRFInfo"`

	// FullName: Полное наименование
	FullName base.Text2000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование
	ShortName *base.Text1000Type `xml:"shortName,omitempty"`

	// Kpp: КПП
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// Inn: ИНН
	Inn *base.InnEntityType `xml:"INN,omitempty"`

	// IncorrectInn: ИНН некорректен или отсутствует в БД Реестра
	IncorrectInn *bool `xml:"incorrectINN,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfoLegalEntityForeignStateInfo: Юридическое лицо иностранного государства
type UnfairSupplierInfoLegalEntityForeignStateInfo struct {
	XMLName xml.Name `xml:"legalEntityForeignStateInfo"`

	// FullName: Полное наименование
	FullName base.Text2000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование
	ShortName *base.Text1000Type `xml:"shortName,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`

	// IncorrectTaxPayerCode: Код налогоплательщика в стране регистрации или его аналог некорректен или отсутствует в БД Реестра
	IncorrectTaxPayerCode *bool `xml:"incorrectTaxPayerCode,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfoIndividualPersonRfinfo: Физическое лицо РФ
type UnfairSupplierInfoIndividualPersonRfinfo struct {
	XMLName xml.Name `xml:"individualPersonRFInfo"`

	// FullName: ФИО
	FullName base.Text2000Type `xml:"fullName"`

	// Inn: ИНН
	Inn *base.InnIndividualType `xml:"INN,omitempty"`

	// IncorrectInn: ИНН некорректен или отсутствует в БД Реестра
	IncorrectInn *bool `xml:"incorrectINN,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfoIndividualPersonForeignStateInfo: Физическое лицо иностранного государства
type UnfairSupplierInfoIndividualPersonForeignStateInfo struct {
	XMLName xml.Name `xml:"individualPersonForeignStateInfo"`

	// FullName: ФИО
	FullName base.Text2000Type `xml:"fullName"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`

	// IncorrectTaxPayerCode: Код налогоплательщика в стране регистрации или его аналог некорректен или отсутствует в БД Реестра
	IncorrectTaxPayerCode *bool `xml:"incorrectTaxPayerCode,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfo: Информация о недобросовестном поставщике (подрядчике, исполнителе)
type UnfairSupplierInfo struct {
	XMLName xml.Name `xml:"unfairSupplierInfo"`

	// UnfairSupplierInfoFounders: Информация об иных лицах, включаемых в Реестр
	Founders []UnfairSupplierInfoFounders `xml:"founders,omitempty"`

	// UnfairSupplierInfoLegalEntityRfinfo: Юридическое лицо РФ
	LegalEntityRfinfo *UnfairSupplierInfoLegalEntityRfinfo `xml:"legalEntityRFInfo,omitempty"`

	// UnfairSupplierInfoLegalEntityForeignStateInfo: Юридическое лицо иностранного государства
	LegalEntityForeignStateInfo *UnfairSupplierInfoLegalEntityForeignStateInfo `xml:"legalEntityForeignStateInfo,omitempty"`

	// UnfairSupplierInfoIndividualPersonRfinfo: Физическое лицо РФ
	IndividualPersonRfinfo *UnfairSupplierInfoIndividualPersonRfinfo `xml:"individualPersonRFInfo,omitempty"`

	// UnfairSupplierInfoIndividualPersonForeignStateInfo: Физическое лицо иностранного государства
	IndividualPersonForeignStateInfo *UnfairSupplierInfoIndividualPersonForeignStateInfo `xml:"individualPersonForeignStateInfo,omitempty"`
}

// AutoExDateInfo: Информация о плановой дате автоматического исключения
type AutoExDateInfo struct {
	XMLName xml.Name `xml:"autoExDateInfo,omitempty"`

	// AutoExDate: Плановая дата автоматического исключения
	AutoExDate string `xml:",any"`
}

// PurchaseInfo: Информация о закупке
type PurchaseInfo struct {
	XMLName xml.Name `xml:"purchaseInfo,omitempty"`

	// PurchaseCode: Идентификационный код закупки
	PurchaseCode []base.IkzCodeType `xml:",any"`
}

// CommonInfo6: Общая информация
type CommonInfo6 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// RegNumber: Номер реестровой записи
	RegNumber base.UnfairSupplier2022RegNumType `xml:"regNumber"`

	// VersionNumber: Номер версии
	VersionNumber string `xml:"versionNumber"`

	// PublishDt: Дата размещения текущей версии документа
	PublishDt string `xml:"publishDT"`

	// FirstVersionPublishDt: Дата размещения первой версии документа
	FirstVersionPublishDt string `xml:"firstVersionPublishDT"`

	// OccurrenceReasonDate: Дата принятия решения о включении в Реестр
	OccurrenceReasonDate string `xml:"occurrenceReasonDate,omitempty"`

	// AppealSubmissionDate: Дата подачи обращения о включении в Реестр
	AppealSubmissionDate string `xml:"appealSubmissionDate,omitempty"`
}

// CreateReasonInfo1: Информация о причинах для внесения в Реестр
type CreateReasonInfo1 struct {
	XMLName xml.Name `xml:"createReasonInfo"`

	// CreateReason: Причина для внесения в Реестр. Допустимые значения: WINNER_DEVIATION - уклонение победителя от заключения контракта ONE_WINNER_DEVIATION - уклонение единственного участника от заключения контракта PARTICIPANT_DEVIATION_IF_WINNER_DEVIATION - уклонение участника размещения заказа от заключения контракта в случае, когда победитель уклонился от заключения контракта CANCEL_CONTRACT - расторжение контракта
	CreateReason base.UnfairSupplier2022CreateReasonEnum `xml:",any"`
}

// UnfairSupplierInfoFoundersType: Тип лица
type UnfairSupplierInfoFoundersType struct {
	XMLName xml.Name `xml:"type,omitempty"`

	// Code: Код по справочнику "Типы иных лиц, добавляемых в РНП"
	Code base.RnpothersCodeType `xml:"code"`

	// Name: Наименование по справочнику "Типы иных лиц, добавляемых в РНП"
	Name *base.Text1000Type `xml:"name,omitempty"`
}

// UnfairSupplierInfoFounders1: Информация об иных лицах, включаемых в Реестр
type UnfairSupplierInfoFounders1 struct {
	XMLName xml.Name `xml:"founders,omitempty"`

	// FullName: Наименование/ФИО
	FullName base.Text1000Type `xml:"fullName"`

	// UnfairSupplierInfoFoundersType: Тип лица
	Type *UnfairSupplierInfoFoundersType `xml:"type,omitempty"`

	// Inn: ИНН
	Inn *base.InnType `xml:"INN,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`

	// IncorrectInnorTaxPayerCode: ИНН или Код налогоплательщика в стране регистрации или его аналог некорректен или отсутствует в БД Реестра
	IncorrectInnorTaxPayerCode *bool `xml:"incorrectINNOrTaxPayerCode,omitempty"`
}

// UnfairSupplierInfoLegalEntityRfinfo1: Юридическое лицо РФ
type UnfairSupplierInfoLegalEntityRfinfo1 struct {
	XMLName xml.Name `xml:"legalEntityRFInfo,omitempty"`

	// FullName: Полное наименование
	FullName base.Text2000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование
	ShortName *base.Text1000Type `xml:"shortName,omitempty"`

	// Kpp: КПП
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// Inn: ИНН
	Inn *base.InnEntityType `xml:"INN,omitempty"`

	// IncorrectInn: ИНН некорректен или отсутствует в БД Реестра
	IncorrectInn *bool `xml:"incorrectINN,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfoLegalEntityForeignStateInfo1: Юридическое лицо иностранного государства
type UnfairSupplierInfoLegalEntityForeignStateInfo1 struct {
	XMLName xml.Name `xml:"legalEntityForeignStateInfo,omitempty"`

	// FullName: Полное наименование
	FullName base.Text2000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование
	ShortName *base.Text1000Type `xml:"shortName,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`

	// IncorrectTaxPayerCode: Код налогоплательщика в стране регистрации или его аналог некорректен или отсутствует в БД Реестра
	IncorrectTaxPayerCode *bool `xml:"incorrectTaxPayerCode,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfoIndividualPersonRfinfo1: Физическое лицо РФ
type UnfairSupplierInfoIndividualPersonRfinfo1 struct {
	XMLName xml.Name `xml:"individualPersonRFInfo,omitempty"`

	// FullName: ФИО
	FullName base.Text2000Type `xml:"fullName"`

	// Inn: ИНН
	Inn *base.InnIndividualType `xml:"INN,omitempty"`

	// IncorrectInn: ИНН некорректен или отсутствует в БД Реестра
	IncorrectInn *bool `xml:"incorrectINN,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfoIndividualPersonForeignStateInfo1: Физическое лицо иностранного государства
type UnfairSupplierInfoIndividualPersonForeignStateInfo1 struct {
	XMLName xml.Name `xml:"individualPersonForeignStateInfo,omitempty"`

	// FullName: ФИО
	FullName base.Text2000Type `xml:"fullName"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.EruztaxPayerCode `xml:"taxPayerCode,omitempty"`

	// IncorrectTaxPayerCode: Код налогоплательщика в стране регистрации или его аналог некорректен или отсутствует в БД Реестра
	IncorrectTaxPayerCode *bool `xml:"incorrectTaxPayerCode,omitempty"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ. Заполнение данного поля означает, что это запись РНП 44ФЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// UnfairContractor615RegistryNum: Реестровый номер подрядной организации в РНПО. Заполнение данного поля означает, что это запись РНПО по ПП РФ № 615
	UnfairContractor615RegistryNum *base.DocumentNumberType `xml:"unfairContractor615RegistryNum,omitempty"`
}

// UnfairSupplierInfo1: Информация о недобросовестном поставщике (подрядчике, исполнителе)
type UnfairSupplierInfo1 struct {
	XMLName xml.Name `xml:"unfairSupplierInfo"`

	// UnfairSupplierInfoFounders: Информация об иных лицах, включаемых в Реестр
	Founders []UnfairSupplierInfoFounders `xml:"founders,omitempty"`

	// UnfairSupplierInfoLegalEntityRfinfo: Юридическое лицо РФ
	LegalEntityRfinfo *UnfairSupplierInfoLegalEntityRfinfo `xml:"legalEntityRFInfo,omitempty"`

	// UnfairSupplierInfoLegalEntityForeignStateInfo: Юридическое лицо иностранного государства
	LegalEntityForeignStateInfo *UnfairSupplierInfoLegalEntityForeignStateInfo `xml:"legalEntityForeignStateInfo,omitempty"`

	// UnfairSupplierInfoIndividualPersonRfinfo: Физическое лицо РФ
	IndividualPersonRfinfo *UnfairSupplierInfoIndividualPersonRfinfo `xml:"individualPersonRFInfo,omitempty"`

	// UnfairSupplierInfoIndividualPersonForeignStateInfo: Физическое лицо иностранного государства
	IndividualPersonForeignStateInfo *UnfairSupplierInfoIndividualPersonForeignStateInfo `xml:"individualPersonForeignStateInfo,omitempty"`
}

// AutoExDateInfo1: Информация о плановой дате автоматического исключения
type AutoExDateInfo1 struct {
	XMLName xml.Name `xml:"autoExDateInfo,omitempty"`

	// AutoExDate: Плановая дата автоматического исключения
	AutoExDate string `xml:",any"`
}

// UnfairSupplier2022ForExcludeInfo: Общая информация о версии исключаемой реестровой записи в ЕИС
type UnfairSupplier2022ForExcludeInfo struct {
	XMLName xml.Name `xml:"unfairSupplier2022ForExcludeInfo"`

	// Uuid: Уникальный идентификатор документа-версии исключаемой реестровой записи в ЕИС
	Uuid base.GuidType `xml:"uuid"`

	// RegNumber: Номер исключаемой реестровой записи
	RegNumber base.UnfairSupplier2022RegNumType `xml:"regNumber"`

	// VersionNumber: Номер версии исключаемой реестровой записи
	VersionNumber string `xml:"versionNumber"`
}

// CommonInfo7: Общая информация
type CommonInfo7 struct {
	XMLName xml.Name `xml:"commonInfo"`

	// ExcludeDt: Дата/время исключения
	ExcludeDt string `xml:"excludeDT"`

	// ExcludeType: Тип исключения из Реестра Допустимые значения: AUTO- автоматическое исключение (запись исключена из Рeeстра по прошествии двух лет); MANUAL - исключено пользователем (запись исключена пользователем из Реестра вручную)
	ExcludeType base.UnfairSupplier2022ExcludeTypeEnum `xml:"excludeType"`
}

// IndividualPersonRfinfoIpinfo: Индивидуальный предприниматель
type IndividualPersonRfinfoIpinfo struct {
	XMLName xml.Name `xml:"IPInfo,omitempty"`

	// Ogrnip: ОГРНИП
	Ogrnip base.OgrnipCodeType `xml:"OGRNIP"`

	// RegDate: Дата регистрации индивидуального предпринимателя
	RegDate string `xml:"regDate"`

	// TaxRegDate: Дата постановки на учет в налоговом органе
	TaxRegDate string `xml:"taxRegDate"`
}

// IndividualPersonRfinfoContactInfo: Контактная информация
type IndividualPersonRfinfoContactInfo struct {
	XMLName xml.Name `xml:"contactInfo"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`
}

// IndividualPersonRfinfo: Физическое лицо РФ
type IndividualPersonRfinfo struct {
	XMLName xml.Name `xml:"individualPersonRFInfo"`

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// Inn: ИНН
	Inn base.InnIndividualType `xml:"INN"`

	// FactAddress: Адрес в пределах места нахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// IndividualPersonRfinfoIpinfo: Индивидуальный предприниматель
	Ipinfo *IndividualPersonRfinfoIpinfo `xml:"IPInfo,omitempty"`

	// IndividualPersonRfinfoContactInfo: Контактная информация
	ContactInfo IndividualPersonRfinfoContactInfo `xml:"contactInfo"`
}

// LegalEntityForeignStateInRafpinfoContactInfo: Контактная информация
type LegalEntityForeignStateInRafpinfoContactInfo struct {
	XMLName xml.Name `xml:"contactInfo"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`
}

// LegalEntityForeignStateInRafpinfo: Аккредитованный филиал или представительство иностранного юридического лица
type LegalEntityForeignStateInRafpinfo struct {
	XMLName xml.Name `xml:"legalEntityForeignStateInRAFPInfo"`

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование организации
	ShortName *base.Text510Type `xml:"shortName,omitempty"`

	// Inn: ИНН
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`

	// RegDate: Дата постановки на учет в налоговом органе
	RegDate string `xml:"regDate"`

	// FactAddress: Адрес в пределах места нахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// LegalEntityForeignStateInRafpinfoContactInfo: Контактная информация
	ContactInfo LegalEntityForeignStateInRafpinfoContactInfo `xml:"contactInfo"`
}

// LegalEntityForeignStateNotInRafpinfoContactInfo: Контактная информация
type LegalEntityForeignStateNotInRafpinfoContactInfo struct {
	XMLName xml.Name `xml:"contactInfo"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`
}

// LegalEntityForeignStateNotInRafpinfo: Юридическое лицо иностранного государства
type LegalEntityForeignStateNotInRafpinfo struct {
	XMLName xml.Name `xml:"legalEntityForeignStateNotInRAFPInfo"`

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование организации
	ShortName *base.Text510Type `xml:"shortName,omitempty"`

	// TaxPayerCode: Аналог идентификационного номера налогоплательщика в соответствии с законодательством иностранного государства
	TaxPayerCode base.TaxPayerCode `xml:"taxPayerCode"`

	// FactAddress: Адрес в пределах места нахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// LegalEntityForeignStateNotInRafpinfoContactInfo: Контактная информация
	ContactInfo LegalEntityForeignStateNotInRafpinfoContactInfo `xml:"contactInfo"`
}

// IndividualPersonForeignStateInfoIpinfo: Индивидуальный предприниматель
type IndividualPersonForeignStateInfoIpinfo struct {
	XMLName xml.Name `xml:"IPInfo,omitempty"`

	// Ogrnip: ОГРНИП
	Ogrnip base.OgrnipCodeType `xml:"OGRNIP"`

	// RegDate: Дата регистрации индивидуального предпринимателя
	RegDate string `xml:"regDate"`

	// TaxRegDate: Дата постановки на учет в налоговом органе
	TaxRegDate string `xml:"taxRegDate"`
}

// IndividualPersonForeignStateInfoContactInfo: Контактная информация
type IndividualPersonForeignStateInfoContactInfo struct {
	XMLName xml.Name `xml:"contactInfo"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`
}

// IndividualPersonForeignStateInfo: Физическое лицо иностранного государства
type IndividualPersonForeignStateInfo struct {
	XMLName xml.Name `xml:"individualPersonForeignStateInfo"`

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// NameLatInfo: ФИО (латинскими буквами)
	NameLatInfo *cmn.PersonType `xml:"nameLatInfo,omitempty"`

	// Inn: ИНН
	Inn *base.InnIndividualType `xml:"INN,omitempty"`

	// TaxPayerCode: Аналог идентификационного номера налогоплательщика в соответствии с законодательством иностранного государства
	TaxPayerCode base.TaxPayerCode `xml:"taxPayerCode"`

	// FactAddress: Адрес в пределах места нахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// IndividualPersonForeignStateInfoIpinfo: Индивидуальный предприниматель
	Ipinfo *IndividualPersonForeignStateInfoIpinfo `xml:"IPInfo,omitempty"`

	// IndividualPersonForeignStateInfoContactInfo: Контактная информация
	ContactInfo IndividualPersonForeignStateInfoContactInfo `xml:"contactInfo"`
}

// ContactInfo2: Контактная информация
type ContactInfo2 struct {
	XMLName xml.Name `xml:"contactInfo"`

	// Email: Адрес электронной почты
	Email base.EMailType `xml:"email"`

	// Phone: Телефон
	Phone base.PhoneType `xml:"phone"`
}

// XSD ComplexType declarations

// ConfirmationType: Тип: Результат обработки
type ConfirmationType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LoadId: Идентификатор загруженных данных
	LoadId *base.GuidType `xml:"loadId,omitempty"`

	// RefDocId: Идентификатор документа в подсистеме, на который сформирован результат обработки
	RefDocId *base.GuidType `xml:"refDocId,omitempty"`

	// ReceiveDt: Дата-время приема пакета, на который формируется подтверждение
	ReceiveDt string `xml:"receiveDT,omitempty"`

	// Result: Результат обработки данных success - обработано успешно; failure - ошибки при обработке; processing - обрабатывается.
	Result base.ConfirmationResultType `xml:"result"`

	// Violations: Выявленные в процессе обработки нарушения и ошибки
	Violations *Violations `xml:"violations,omitempty"`

	// RefId: Идентификатор обработанного пакета данных
	RefId base.GuidType `xml:"refId"`

	// ObjectType: Тип документа, на который формируется результат обработки
	ObjectType *base.Text2000Type `xml:"objectType,omitempty"`
}

// ParElectronicComplaintType: Тип: Информация об электронной жалобе, сформированной в ЛКП
type ParElectronicComplaintType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП
	LkpUuid base.GuidType `xml:"lkpUuid"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании жалобы поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ApplicantInfo: Заявитель
	ApplicantInfo ApplicantInfoType `xml:"applicantInfo"`

	// ObjectInfo: Предмет жалобы
	ObjectInfo *ObjectInfo `xml:"objectInfo,omitempty"`

	// SubjectsInfo: Информация о субъектах жалобы
	SubjectsInfo SubjectsInfo `xml:"subjectsInfo"`

	// Koinfo: Информация о контрольном органе в сфере закупок
	Koinfo base.OrganizationRef `xml:"KOInfo"`

	// ExperienceConfirmationInfo: Подтверждение опыта участника закупок
	ExperienceConfirmationInfo *ExperienceConfirmationInfo `xml:"experienceConfirmationInfo,omitempty"`

	// ContactInfo: Контактные данные участника закупок
	ContactInfo ContactInfo `xml:"contactInfo"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком. При передаче заполняется поле "Содержимое файла электронного документа" (content)
	ParPrintFormInfo *cmn.LkpPrintFormType `xml:"parPrintFormInfo,omitempty"`

	// NoticeOrgsInfo: Организации, в адрес которых осуществляется рассылка уведомлений Игнорируется при приеме проекта из внешней системы
	NoticeOrgsInfo *NoticeOrgsInfo `xml:"noticeOrgsInfo,omitempty"`
}

// ParElectronicComplaintCancelType: Тип: Информация об отзыве электронной жалобы, сформированной в ЛКП
type ParElectronicComplaintCancelType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП
	LkpUuid base.GuidType `xml:"lkpUuid"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании отзыва жалобы поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RegNumber: Номер реестровой записи жалобы
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// PublishDt: Дата размещения документа в ЕИС. Не заполняется при подписании отзыва жалобы поставщиком. Заполняется датой размещении отзыва жалобы в РЖ
	PublishDt string `xml:"publishDT,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком
	ParPrintFormInfo *cmn.LkpPrintFormType `xml:"parPrintFormInfo,omitempty"`

	// PrintFormFieldsInfo: Дополнительная информация для печатной формы
	PrintFormFieldsInfo *PrintFormFieldsInfo `xml:"printFormFieldsInfo,omitempty"`
}

// ParElectronicComplaintAcceptType: Тип: Информация о принятии к рассмотрению электронной жалобы, сформированной в ЛКП
type ParElectronicComplaintAcceptType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// CommonInfo: Общая информация о принятии жалобы к рассмотрению
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ComplaintInfo: Информация о жалобе, по которой формируется информация о принятии к рассмотрению
	ComplaintInfo ComplaintInfo `xml:"complaintInfo"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа. Игнорируется при приеме, заполняется при передаче
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`

	// ExtPrintFormInfo: Электронный документ, полученный из внешней системы. При приеме контролируется обязательность заполнения блока
	ExtPrintFormInfo *cmn.ExtPrintFormType `xml:"extPrintFormInfo,omitempty"`
}

// ParElectronicComplaintRefusalType: Тип: Информация об отказе в рассмотрении электронной жалобы, сформированной в ЛКП
type ParElectronicComplaintRefusalType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// CommonInfo: Общая информация об отказе в рассмотрении жалобы
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ComplaintInfo: Информация о жалобе, по которой формируется информация об отказе в рассмотрении
	ComplaintInfo ComplaintInfo `xml:"complaintInfo"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа. Игнорируется при приеме, заполняется при передаче
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`

	// ExtPrintFormInfo: Электронный документ, полученный из внешней системы При приеме контролируется обязательность заполнения блока
	ExtPrintFormInfo *cmn.ExtPrintFormType `xml:"extPrintFormInfo,omitempty"`
}

// NoticeType: Тип: Уведомление о наступлении в ЕИС события, которое связано с жалобой, сформированной в ЛКП
type NoticeType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор уведомления в ЕИС
	Uuid base.GuidType `xml:"uuid"`

	// RegNumber: Номер реестровой записи жалобы
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// PublishDt: Дата размещения документа в ЕИС
	PublishDt string `xml:"publishDT"`

	// Href: Гиперссылка на размещённый в ЕИС документ
	Href *base.HrefType `xml:"href,omitempty"`

	// DsUid: Идентификатор документа в ХД. Поле не заполняется при приеме.
	DsUid *base.GuidType `xml:"dsUid,omitempty"`

	// NoticeTypeInfo: Информация о типе события
	NoticeTypeInfo NoticeTypeInfo `xml:"noticeTypeInfo"`

	// UserInfo: Информация о пользователе, совершившем действие, связанное с уведомлением
	UserInfo *cmn.PersonType `xml:"userInfo,omitempty"`

	// OrganizationInfo: Информация об организации пользователя, совершившего действие, связанное с событием
	OrganizationInfo *base.OrganizationRef `xml:"organizationInfo,omitempty"`

	// SignatureInfo: Электронная подпись электронного документа в ХД
	SignatureInfo []SignatureInfo `xml:"signatureInfo,omitempty"`
}

// ClosedParElectronicComplaintType: Тип: Информация об сокрытой электронной жалобе, сформированной в ЛКП
type ClosedParElectronicComplaintType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП
	LkpUuid base.GuidType `xml:"lkpUuid"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании жалобы поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ApplicantInfo: Заявитель
	ApplicantInfo ApplicantInfoType `xml:"applicantInfo"`

	// ObjectInfo: Предмет жалобы
	ObjectInfo *ObjectInfo `xml:"objectInfo,omitempty"`

	// SubjectsInfo: Информация о субъектах жалобы
	SubjectsInfo SubjectsInfo `xml:"subjectsInfo"`

	// Koinfo: Информация о контрольном органе в сфере закупок
	Koinfo base.OrganizationRef `xml:"KOInfo"`

	// ExperienceConfirmationInfo: Подтверждение опыта участника закупок
	ExperienceConfirmationInfo *ExperienceConfirmationInfo `xml:"experienceConfirmationInfo,omitempty"`

	// ContactInfo: Контактные данные участника закупок
	ContactInfo ContactInfo `xml:"contactInfo"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком. При передаче заполняется поле "Содержимое файла электронного документа" (content)
	ParPrintFormInfo *cmn.LkpPrintFormType `xml:"parPrintFormInfo,omitempty"`

	// NoticeOrgsInfo: Организации, в адрес которых осуществляется рассылка уведомлений Игнорируется при приеме проекта из внешней системы
	NoticeOrgsInfo *NoticeOrgsInfo `xml:"noticeOrgsInfo,omitempty"`
}

// ClosedParElectronicComplaintCancelType: Тип: Информация об отзыве сокрытой электронной жалобы, сформированной в ЛКП
type ClosedParElectronicComplaintCancelType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// LkpUuid: Уникальный идентификатор документа в ЛКП
	LkpUuid base.GuidType `xml:"lkpUuid"`

	// Uuid: Уникальный идентификатор документа в ЕИС. Не заполняется при подписании отзыва жалобы поставщиком. Заполняется при размещении
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RegNumber: Номер реестровой записи жалобы
	RegNumber base.ControlRegistersRegNumberType `xml:"regNumber"`

	// PublishDt: Дата размещения документа в ЕИС. Не заполняется при подписании отзыва жалобы поставщиком. Заполняется датой размещении отзыва жалобы в РЖ
	PublishDt string `xml:"publishDT,omitempty"`

	// ParPrintFormInfo: Печатная форма документа, подписанного поставщиком
	ParPrintFormInfo *cmn.LkpPrintFormType `xml:"parPrintFormInfo,omitempty"`

	// PrintFormFieldsInfo: Дополнительная информация для печатной формы
	PrintFormFieldsInfo *PrintFormFieldsInfo `xml:"printFormFieldsInfo,omitempty"`
}

// ApprovalType: Тип: Обращение в контрольный орган
type ApprovalType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid base.GuidType `xml:"uuid"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// CustomerInfo: Информация о заказчике
	CustomerInfo CustomerInfo `xml:"customerInfo"`

	// PowersCustomerOrgInfo: Сведения об организации, действующей за заказчика (УО. УУ. ОПЗ)
	PowersCustomerOrgInfo *PowersCustomerOrgInfo `xml:"powersCustomerOrgInfo,omitempty"`

	// Koinfo: Информация о контрольном органе в сфере закупок
	Koinfo OrganizationInfoType `xml:"KOInfo"`

	// ApprovalInfo: Информация об обращении
	ApprovalInfo ApprovalInfo `xml:"approvalInfo"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`

	// ExtPrintFormInfo: Электронный документ, полученный из внешней системы. При приеме контролируется обязательность заполнения блока
	ExtPrintFormInfo *cmn.ExtPrintFormType `xml:"extPrintFormInfo,omitempty"`
}

// ApprovalTransferType: Тип: Информация о передаче обращения в другой контрольный орган
type ApprovalTransferType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// PublishDt: Дата размещения документа в ЕИС
	PublishDt string `xml:"publishDT,omitempty"`

	// RegNumber: Номер реестровой записи обращения
	RegNumber base.ApprovalRegNumType `xml:"regNumber"`

	// ReasonText: Причина передачи
	ReasonText base.Text2000Type `xml:"reasonText"`

	// TransferingKoinfo: Информация о контрольном органе в сфере закупок, передающем обращение
	TransferingKoinfo OrganizationInfoType `xml:"transferingKOInfo"`

	// ReceivingKoinfo: Информация о контрольном органе в сфере закупок, принимающем обращение
	ReceivingKoinfo OrganizationInfoType `xml:"receivingKOInfo"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`

	// ExtPrintFormInfo: Электронный документ, полученный из внешней системы. При приеме контролируется обязательность заполнения блока
	ExtPrintFormInfo *cmn.ExtPrintFormType `xml:"extPrintFormInfo,omitempty"`
}

// ApprovalMismatchType: Тип: Уведомление о выявленных в обращении несоответствиях
type ApprovalMismatchType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid *base.GuidType `xml:"uuid,omitempty"`

	// RegNumber: Номер реестровой записи уведомления
	RegNumber base.ApprovalMismatchRegNumType `xml:"regNumber"`

	// PublishDt: Дата размещения документа в ЕИС
	PublishDt string `xml:"publishDT,omitempty"`

	// ApprovalCommonInfo: Общая информация об обращении
	ApprovalCommonInfo ApprovalCommonInfo `xml:"approvalCommonInfo"`

	// Koinfo: Информация о контрольном органе в сфере закупок
	Koinfo OrganizationShortInfoType `xml:"KOInfo"`

	// CustomerInfo: Информация о заказчике
	CustomerInfo OrganizationShortInfoType `xml:"customerInfo"`

	// PowersCustomerOrgInfo: Сведения об организации, действующей за заказчика (ОПЗ)
	PowersCustomerOrgInfo *OrganizationShortInfoType `xml:"powersCustomerOrgInfo,omitempty"`

	// Foundation: Основания направления уведомления (выявленное несоответствие)
	Foundation base.Text2000Type `xml:"foundation"`

	// AttachmentsInfo: Информация о прикрепленных документах
	AttachmentsInfo *cmn.AttachmentListType `xml:"attachmentsInfo,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`

	// ExtPrintFormInfo: Электронный документ, полученный из внешней системы. При приеме контролируется обязательность заполнения блока
	ExtPrintFormInfo *cmn.ExtPrintFormType `xml:"extPrintFormInfo,omitempty"`

	// PrintFormFieldsInfo: Дополнительная информация для печатной формы
	PrintFormFieldsInfo *PrintFormFieldsInfo `xml:"printFormFieldsInfo,omitempty"`
}

// ApprovalLegalEntityRfinfoType: Тип: Юридическое лицо РФ в обращении в контрольный орган
type ApprovalLegalEntityRfinfoType struct {
	XMLName xml.Name

	// FullName: Полное наименование
	FullName base.Text2000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование
	ShortName *base.Text2000Type `xml:"shortName,omitempty"`

	// Inn: ИНН
	Inn base.InnEntityType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`

	// Oktmo: Территориально-муниципальное образование организации по ОКТМО
	Oktmo base.Oktmoref `xml:"OKTMO"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// OrgFactAddress: Адрес местонахождения организации
	OrgFactAddress base.Text2000Type `xml:"orgFactAddress"`

	// ContactEmail: Электронная почта
	ContactEmail *base.EMailType `xml:"contactEMail,omitempty"`
}

// ApprovalLegalEntityForeignStateInfoType: Тип: Юридическое лицо иностранного государства в обращении в контрольный орган
type ApprovalLegalEntityForeignStateInfoType struct {
	XMLName xml.Name

	// FullName: Полное наименование
	FullName base.Text2000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование
	ShortName *base.Text2000Type `xml:"shortName,omitempty"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.TaxPayerCode `xml:"taxPayerCode,omitempty"`

	// Inn: ИНН
	Inn *base.InnEntityType `xml:"INN,omitempty"`

	// Kpp: КПП
	Kpp *base.KppType `xml:"KPP,omitempty"`

	// Oktmo: Территориально-муниципальное образование организации по ОКТМО
	Oktmo base.Oktmoref `xml:"OKTMO"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// OrgFactAddress: Адрес местонахождения организации
	OrgFactAddress base.Text2000Type `xml:"orgFactAddress"`

	// ContactEmail: Электронная почта
	ContactEmail *base.EMailType `xml:"contactEMail,omitempty"`
}

// ApprovalIndividualPersonRfinfoType: Тип: Физическое лицо РФ в обращении в контрольный орган
type ApprovalIndividualPersonRfinfoType struct {
	XMLName xml.Name

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// Inn: ИНН
	Inn base.InnIndividualType `xml:"INN"`

	// Oktmo: Территориально-муниципальное образование организации по ОКТМО
	Oktmo base.Oktmoref `xml:"OKTMO"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// FactAddress: Адрес местонахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// ContactEmail: Электронная почта
	ContactEmail *base.EMailType `xml:"contactEMail,omitempty"`
}

// ApprovalIndividualPersonForeignStateInfoType: Тип: Физическое лицо иностранного государства в обращении в контрольный орган
type ApprovalIndividualPersonForeignStateInfoType struct {
	XMLName xml.Name

	// NameInfo: ФИО
	NameInfo cmn.PersonType `xml:"nameInfo"`

	// TaxPayerCode: Код налогоплательщика в стране регистрации или его аналог
	TaxPayerCode *base.TaxPayerCode `xml:"taxPayerCode,omitempty"`

	// Inn: ИНН
	Inn *base.InnIndividualType `xml:"INN,omitempty"`

	// Oktmo: Территориально-муниципальное образование организации по ОКТМО
	Oktmo base.Oktmoref `xml:"OKTMO"`

	// ContractorRegistryNum: Номер реестровой записи в ЕРУЗ
	ContractorRegistryNum *base.EruzRegistryNumType `xml:"contractorRegistryNum,omitempty"`

	// FactAddress: Адрес местонахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// ContactEmail: Электронная почта
	ContactEmail *base.EMailType `xml:"contactEMail,omitempty"`
}

// UnfairSupplier2022Type: Тип: Запись Реестра недобросовестных поставщиков (РНП) с 01.04.2022 (Запись РНПО по ПП РФ № 615)
type UnfairSupplier2022Type struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid base.GuidType `xml:"uuid"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ApproveOrgInfo: Уполномоченный орган, осуществивший включение информации и ведущий запись в Реестре
	ApproveOrgInfo *cmn.OrganizationRefType `xml:"approveOrgInfo,omitempty"`

	// CreateReasonInfo: Информация о причинах для внесения в Реестр
	CreateReasonInfo CreateReasonInfo `xml:"createReasonInfo"`

	// RefusalDueToCustSanctions: Отказ поставщика (подрядчика, исполнителя) от исполнения контракта по причине введения в отношении заказчика санкций и (или) мер ограничительного характера
	RefusalDueToCustSanctions *bool `xml:"refusalDueToCustSanctions,omitempty"`

	// UnfairSupplierInfo: Информация о недобросовестном поставщике (подрядчике, исполнителе)
	UnfairSupplierInfo UnfairSupplierInfo `xml:"unfairSupplierInfo"`

	// AutoExDateInfo: Информация о плановой дате автоматического исключения
	AutoExDateInfo *AutoExDateInfo `xml:"autoExDateInfo,omitempty"`

	// ModificationReason: Причина внесения изменений. Игнорируется при приеме, добавлено для печатной формы
	ModificationReason *base.Text1000Type `xml:"modificationReason,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`
}

// UnfairSupplierIkztype: Тип: Запись Реестра недобросовестных поставщиков (РНП) с 01.04.2022 (Запись РНПО по ПП РФ № 615) со сведениями об ИКЗ
type UnfairSupplierIkztype struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// PurchaseInfo: Информация о закупке
	PurchaseInfo *PurchaseInfo `xml:"purchaseInfo,omitempty"`

	// Uuid: Уникальный идентификатор документа в ЕИС
	Uuid base.GuidType `xml:"uuid"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// ApproveOrgInfo: Уполномоченный орган, осуществивший включение информации и ведущий запись в Реестре
	ApproveOrgInfo *cmn.OrganizationRefType `xml:"approveOrgInfo,omitempty"`

	// CreateReasonInfo: Информация о причинах для внесения в Реестр
	CreateReasonInfo CreateReasonInfo `xml:"createReasonInfo"`

	// RefusalDueToCustSanctions: Отказ поставщика (подрядчика, исполнителя) от исполнения контракта по причине введения в отношении заказчика санкций и (или) мер ограничительного характера
	RefusalDueToCustSanctions *bool `xml:"refusalDueToCustSanctions,omitempty"`

	// UnfairSupplierInfo: Информация о недобросовестном поставщике (подрядчике, исполнителе)
	UnfairSupplierInfo UnfairSupplierInfo `xml:"unfairSupplierInfo"`

	// AutoExDateInfo: Информация о плановой дате автоматического исключения
	AutoExDateInfo *AutoExDateInfo `xml:"autoExDateInfo,omitempty"`

	// ModificationReason: Причина внесения изменений. Игнорируется при приеме, добавлено для печатной формы
	ModificationReason *base.Text1000Type `xml:"modificationReason,omitempty"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`
}

// UnfairSupplier2022ExcludeType: Тип: Исключение записи Реестра недобросовестных поставщиков (РНП) с 01.04.2022 (Исключение записи РНПО по ПП РФ № 615)
type UnfairSupplier2022ExcludeType struct {
	XMLName xml.Name

	// SchemeVersion: Версия схемы
	SchemeVersion base.SchemeVersionType `xml:"schemeVersion,attr"`

	// Uuid: Уникальный идентификатор документа-исключения в ЕИС
	Uuid base.GuidType `xml:"uuid"`

	// UnfairSupplier2022ForExcludeInfo: Общая информация о версии исключаемой реестровой записи в ЕИС
	UnfairSupplier2022ForExcludeInfo UnfairSupplier2022ForExcludeInfo `xml:"unfairSupplier2022ForExcludeInfo"`

	// CommonInfo: Общая информация
	CommonInfo CommonInfo `xml:"commonInfo"`

	// PrintFormInfo: Печатная форма документа
	PrintFormInfo *cmn.PrintFormType `xml:"printFormInfo,omitempty"`
}

// ApplicantInfoType: Тип: Сведения о заявителе
type ApplicantInfoType struct {
	XMLName xml.Name

	// LegalEntityRfinfo: Юридическое лицо РФ
	LegalEntityRfinfo *LegalEntityRfinfoType `xml:"legalEntityRFInfo,omitempty"`

	// FilialLegalEntityRfinfo: Филиал юридического лица РФ
	FilialLegalEntityRfinfo *LegalEntityRfinfoType `xml:"filialLegalEntityRFInfo,omitempty"`

	// IndividualPersonRfinfo: Физическое лицо РФ
	IndividualPersonRfinfo *IndividualPersonRfinfo `xml:"individualPersonRFInfo,omitempty"`

	// LegalEntityForeignStateInRafpinfo: Аккредитованный филиал или представительство иностранного юридического лица
	LegalEntityForeignStateInRafpinfo *LegalEntityForeignStateInRafpinfo `xml:"legalEntityForeignStateInRAFPInfo,omitempty"`

	// LegalEntityForeignStateNotInRafpinfo: Юридическое лицо иностранного государства
	LegalEntityForeignStateNotInRafpinfo *LegalEntityForeignStateNotInRafpinfo `xml:"legalEntityForeignStateNotInRAFPInfo,omitempty"`

	// IndividualPersonForeignStateInfo: Физическое лицо иностранного государства
	IndividualPersonForeignStateInfo *IndividualPersonForeignStateInfo `xml:"individualPersonForeignStateInfo,omitempty"`
}

// LegalEntityRfinfoType: Тип: Сведения о юридическом лице РФ
type LegalEntityRfinfoType struct {
	XMLName xml.Name

	// FullName: Полное наименование организации
	FullName base.Text1000Type `xml:"fullName"`

	// ShortName: Сокращенное наименование организации
	ShortName *base.Text510Type `xml:"shortName,omitempty"`

	// Okopf: Сведения об организационно-правовой форме из ЕГРЮЛ
	Okopf *base.Okopfref `xml:"OKOPF,omitempty"`

	// Inn: ИНН
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП
	Kpp base.KppType `xml:"KPP"`

	// RegDate: Дата постановки на учет в налоговом органе
	RegDate string `xml:"regDate"`

	// FactAddress: Адрес в пределах места нахождения
	FactAddress base.Text2000Type `xml:"factAddress"`

	// ContactInfo: Контактная информация
	ContactInfo ContactInfo `xml:"contactInfo"`
}

// KladrPlaceType: Тип: Место рассмотрения жалобы
type KladrPlaceType struct {
	XMLName xml.Name

	// Kladr: Код КЛАДР
	Kladr *KladrType `xml:"kladr,omitempty"`

	// DeliveryPlace: Место
	DeliveryPlace base.Text2000Type `xml:"deliveryPlace"`
}

// KladrType: Тип: Адрес по КЛАДР
type KladrType struct {
	XMLName xml.Name

	// KladrCode: Код КЛАДР
	KladrCode base.KladrCodeType `xml:"kladrCode"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника КЛАДР по коду КЛАДР
	FullName *base.KladrTextType `xml:"fullName,omitempty"`
}

// OrganizationInfoType: Тип: Сведения об организации
type OrganizationInfoType struct {
	XMLName xml.Name

	// ShortName: Краткое наименование
	ShortName *base.Text2000Type `xml:"shortName,omitempty"`

	// Inn: ИНН организации
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП организации
	Kpp base.KppType `xml:"KPP"`

	// Address: Адрес места нахождения
	Address base.Text2000Type `xml:"address"`

	// RegNum: Код по СПЗ. В случае если организация идентифицируется по коду СвР, а код СПЗ неизвестен, необходимо заполнить данное поле значением 00000000000, и обязательно указать код СвР
	RegNum SpzNumType `xml:"regNum"`

	// ConsRegistryNum: Код по Сводному Реестру. Должен быть заполнен в случае, если в поле regNum указано значение 00000000000
	ConsRegistryNum *ConsRegistryNumType `xml:"consRegistryNum,omitempty"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	FullName *Text2000Type `xml:"fullName,omitempty"`
}

// OrganizationShortInfoType: Тип: Краткие сведения об организации
type OrganizationShortInfoType struct {
	XMLName xml.Name

	// Inn: ИНН организации
	Inn base.InnOrganizationType `xml:"INN"`

	// Kpp: КПП организации
	Kpp base.KppType `xml:"KPP"`

	// RegNum: Код по СПЗ. В случае если организация идентифицируется по коду СвР, а код СПЗ неизвестен, необходимо заполнить данное поле значением 00000000000, и обязательно указать код СвР
	RegNum SpzNumType `xml:"regNum"`

	// ConsRegistryNum: Код по Сводному Реестру. Должен быть заполнен в случае, если в поле regNum указано значение 00000000000
	ConsRegistryNum *ConsRegistryNumType `xml:"consRegistryNum,omitempty"`

	// FullName: Полное наименование. Игнорируется при приеме. При передаче заполняется значением из справочника "Сводный перечень заказчиков (СПЗ)" (nsiOrganizationList)
	FullName *Text2000Type `xml:"fullName,omitempty"`
}

// SubjectInfoType: Тип: Информация о субъекте жалобы
type SubjectInfoType struct {
	XMLName xml.Name

	// CustomerInfo: Заказчик
	CustomerInfo *OrganizationInfoType `xml:"customerInfo,omitempty"`

	// AuthorityInfo: Уполномоченный орган
	AuthorityInfo *OrganizationInfoType `xml:"authorityInfo,omitempty"`

	// AuthorityAgencyInfo: Уполномоченное учреждение
	AuthorityAgencyInfo *OrganizationInfoType `xml:"authorityAgencyInfo,omitempty"`

	// CommissionInfo: Комиссия по осуществлению закупок
	CommissionInfo *OrganizationInfoType `xml:"commissionInfo,omitempty"`

	// SpecializedInfo: Специализированная организация
	SpecializedInfo *OrganizationInfoType `xml:"specializedInfo,omitempty"`

	// ContractServiceOfficerInfo: Должностное лицо контрактной службы
	ContractServiceOfficerInfo *OrganizationInfoType `xml:"contractServiceOfficerInfo,omitempty"`

	// ContractServiceInfo: Контрактный управляющий
	ContractServiceInfo *OrganizationInfoType `xml:"contractServiceInfo,omitempty"`

	// LegalEntity44Info: Юридические лица, осуществляющие полномочия заказчика на осуществление закупок на основании договора (соглашения) в соответствии с частью 6 статьи 15 Федерального закона № 44-ФЗ
	LegalEntity44Info *OrganizationInfoType `xml:"legalEntity44Info,omitempty"`

	// Guarantor: Гарант
	Guarantor *OrganizationInfoType `xml:"guarantor,omitempty"`
}

// ViolationType: Тип: Нарушение приема
type ViolationType struct {
	XMLName xml.Name

	// ErrCode: Код ошибки
	ErrCode base.Text10Type `xml:"errCode"`

	// Level: Тип: error - Ошибка warning - Предупреждение
	Level base.ViolationLevelType `xml:"level"`

	// Name: Наименование
	Name base.Text200Type `xml:"name"`

	// Description: Описание
	Description *base.Text2000Type `xml:"description,omitempty"`

	// FullErrorLog: Полный текст ошибки
	FullErrorLog string `xml:"fullErrorLog,omitempty"`
}

// XSD SimpleType declarations

// Agreement223RegNumType: Тип: Номер реестровой записи договора 223 ФЗ
type Agreement223RegNumType string

// ControlResultType: Тип: Тип результата контроля
type ControlResultType string

const ControlResultTypeComplaint ControlResultType = "complaint"

const ControlResultTypeCheckresult ControlResultType = "checkResult"

// ApprovalTypeType: Тип: Тип обращения. singleParContract - обращение о согласовании заключения контракта с единственным поставщиком (подрядчиком, исполнителем); unfairSupplier2022 - обращение о включении в РНП
type ApprovalTypeType string

const ApprovalTypeTypeSingleparcontract ApprovalTypeType = "singleParContract"

const ApprovalTypeTypeUnfairsupplier2022 ApprovalTypeType = "unfairSupplier2022"
